rwengine/openrw

rwgame/RWGame.cpp
Obviously it would be nice to generate a unique name for the screenshot but this at least removes the hardcoded directory.
=> Don't hardcode screenshot directory (still hardcodes filename)

CMakeLists.txt, rwengine/include/data/CutsceneData.hpp, rwengine/include/script/ScriptMachine.hpp, rwengine/src/engine/GameData.cpp
Hi,
beside some small compilation errors, this also fixes `findPathRealCase` in `rwengine/src/engine/GameData.cpp` on OS X.
On a side note, it does not correctly render yet. (first of, the shaders do not even compile because of core/compatibility profile issues on OS X)
(This was tested on 10.11.5)
=> OS X port of OpenRW

CMakeLists.txt
GLM requires using the new config mode as it only ships a
glmConfig.cmake.
more info:
http://stackoverflow.com/q/34634850/4453524
https://cmake.org/cmake/help/latest/command/find_package.html
fixes https://github.com/danhedron/openrw/issues/41
=> [CMake] Use find_package config mode for GLM

.gitmodules, cmake/external/inih.cmake
ExternalProject use is discouraged.
- Most package build systems do not allow any fetching on
configure/build stage
- It's insecure the way it's used now, as it does not specify commit
hash, so it may fetch whatever malicous code and it'll come
unoticed
=> Use inih as git submodule

CMakeLists.txt, rwgame/GameConfig.cpp
For now, there's only single OS-dependent bit of code, it it should be handled on FreeBSD just like on Linux. While here, change macro testing from #if XXX to #if defined(XXX), this is clener and not prone to
"undefined macro" errors
=> Add FreeBSD support

rwgame/debugstate.cpp
This adds a debug menu option to spawn a Yakuza Stinger (ID 136).
It's 3 units in front of the player, always rotated 90 degree on the vertical axis so it's ready to be entered.
It's fairly simple to replace the car with any other. Just pick an ID.
=> Add car spawner to debug menu

cmake/modules/FindGLM.cmake
This was removed in upstream in the following commit:
https://github.com/g-truc/glm/commit/62a7daddcf082f754000fc5e42d7bcdf93c895f7
=> Copy FindGLM.cmake from glm

rwgame/debugstate.cpp
This makes testing easier (hopefully).
- "Jump to Debug Camera" places the player in front of the debug camera. Useful if you want to get somewhere fast.
I had to rework some of the JumpCharacter function to make this possible.
- "Flip Vehicle" (only shown while in a vehicle) will flip the vehicle upside down, however, it currently keeps its spin and velocity. It's still good enough to avoid mission failure.
=> Debug features: "Jump to Debug Camera" and "Flip Vehicle"

rwengine/include/data/ObjectData.hpp, rwengine/include/render/OpenGLRenderer.hpp, rwengine/src/objects/InstanceObject.cpp, rwengine/src/render/ObjectRenderer.cpp, rwengine/src/render/OpenGLRenderer.cpp, rwengine/src/render/TextRenderer.cpp
4 commits, 4 comments:
* First this replaces the ObjectData flags for SA with those from GTA3.
We can still re-add the code later when working on SA. I think this was added for SA by accident anyway?
This also made it necessary to change some damage handler.
(No idea what the 80 means btw, I think there should be an enum for these values..)
* Then add a depth write function to the OpenGL Renderer
(Unused at this point)
* During the previous change I noticed that the `blendEnabled` bool is never actually set (which always forces enabled `GL_BLEND`). However, setting it breaks the renderer because the blend state is not recovered on Renderer invalidation and even when adding that it's still broken because not everything invalidates the renderer..
I didn't want to fix it as part of this …
=> Enable / Disable depth writing

rwlib/CMakeLists.txt, rwlib/source/loaders/LoaderIMG.cpp, rwlib/source/loaders/LoaderSDT.cpp, rwlib/source/loaders/LoaderSDT.hpp
Seems to work. It's mostly a copy & paste job from the LoaderIMG which already existed.
Successfully exported an audio clip using
```
LoaderSDT loaderSdt;
loaderSdt.load(config.getGameDataPath() + "/audio/sfx");
loaderSdt.saveAsset(25, "icecream.wav");
```
Didn't test much more than that though.
---
I did some cleanup in the messy IMG loader while I was at it.
There are still a lot of bad things in there.. (missing error handling and bad / incomplete error handling)
Whenever I touched code I tried to adjust to the a new (?) code style. I think we should just run a code formatter over this at some point anyway (soon, so before more developers start working on it).
---
I wasn't sure wether to name this LoaderSDT or LoaderRAW (closer to LoaderIMG) but felt LoaderSDT was more expressive.
=> Loader for SDT/RAW audio archives

rwengine/include/objects/CharacterObject.hpp, rwengine/src/script/modules/ObjectModule.cpp
`master` lacks these opcodes and crashes when going near the fish factory. This fixes that.
This stubs all functions necessary for the FISHGEN thread which generates triads near the factory.
---
I've only implemented one of the functions which is used to give characters a weapon.
It appears to be working fine. Also, I've guarded the check by turning the weapon inventory into an `std::array`.
One could possibly use `std::array::at()` but I wasn't sure as the rest of the code uses the `RW_CHECK` macro instead of throwing exceptions directly.
There are a couple of other bugs which prevent this from being useful (such as cars spawning near the factory) but I'll PR them seperately with fixes for LUIGI2. Some other things (char cleanup, objectives to be hostile towards player, ..) are harder to …
=> Fix FISHGEN

rwengine/include/render/TextRenderer.hpp, rwengine/src/engine/ScreenText.cpp, rwengine/src/render/TextRenderer.cpp, rwgame/DrawUI.cpp
I've used [this wiki page](http://www.gtamodding.com/wiki/00BA) to document (in the form of comments) each font style of the Big texts and the HighPriority messages.
The documentation (to my knowledge) should be complete, though I'm a manly man and I lack in giving colors a funny name so color names might not be precise.
After documenting I started an implementation.
Except for the `duration` I've tried to implement everything.
Note that the `y` position is set to the intended baseline position (where letters except for "q, y, p" etc. start from the bottom) but OpenRW has no way to respect this properly so texts might be off on the vertical axis.
I also didn't verify the font size in my implementation. and I assume that's also bad currently.
I wasn't sure around the wrap size either and …
=> Improve text styles

.travis.yml, CMakeLists.txt, tests/CMakeLists.txt, tests/test_FileIndex.cpp, tests/test_GameData.cpp, tests/test_GameWorld.cpp, tests/test_animation.cpp, tests/test_archive.cpp, tests/test_buoyancy.cpp, tests/test_character.cpp, tests/test_chase.cpp, tests/test_cutscene.cpp, tests/test_data.cpp, tests/test_globals.hpp, tests/test_items.cpp, tests/test_lifetime.cpp, tests/test_loaderdff.cpp, tests/test_object_data.cpp, tests/test_pickup.cpp, tests/test_rwbstream.cpp, tests/test_text.cpp, tests/test_trafficdirector.cpp, tests/test_vehicle.cpp, tests/test_weapon.cpp
This builds OpenRW on Linux and adds a flag to disable tests that require game data.
As many of these tests as possible should be modified to remove the dependency so we can keep good coverage.
=> Add Travis CI

rwengine/include/engine/GameWorld.hpp, rwengine/include/objects/PickupObject.hpp, rwengine/include/script/ScriptTypes.hpp, rwengine/src/engine/GameWorld.cpp, rwengine/src/script/ScriptMachine.cpp, rwengine/src/script/ScriptTypes.cpp, rwengine/src/script/modules/GameModule.cpp, rwengine/src/script/modules/ObjectModule.cpp, rwgame/ingamestate.cpp
This provides a proper implementation for 0x032B and cleans up the implementation of 0x0213.
- Move the creation of Pickups into `GameWorld`, where it belongs.
- Improve the Integer value conversion of `SCMOpcodeParameter` and use it instead.
- Use `PickupObject` for non-weapon pickups.
- use `createPickup` in rwgame.
=> Fix opcodes 0x0213 & 0x032B

rwengine/include/script/ScriptTypes.hpp, rwengine/src/script/modules/GameModule.cpp, rwengine/src/script/modules/VMModule.cpp
PR extends `master` towards being able to add vehicle missions.
This has been extracted from a larger PR which will follow soon.
There is nothing too interesting here.
However, I'd like to draw your attention to the input hack which maps the `player->isRunning()` return value to the script button-state-getter-opcodes sub-mission key.
This works because OpenRW always updates `isRunning` even if the player is in a car. It also means you can start the vehicle missions by pressing shift (or whatever the sprint key may be) while in a mission vehicle.
I'm aware that this is a cruel hack, but OpenRW doesn't maintain a input state yet. IMHO this is fine as a temporary fix. I'll create an issue about this once this PR is merged too, to remind us of this ugly piece.
None of this was tested much and …
=> Mission vehicle base

rwengine/include/ai/TrafficDirector.hpp, rwengine/include/data/VehicleGenerator.hpp, rwengine/include/engine/GameState.hpp, rwengine/include/engine/GameWorld.hpp, rwengine/src/ai/TrafficDirector.cpp, rwengine/src/engine/GameWorld.cpp, rwengine/src/engine/SaveGame.cpp, rwengine/src/script/modules/GameModule.cpp, rwgame/RWGame.cpp, tests/test_lifetime.cpp, tests/test_trafficdirector.cpp
This adds:
- spawning of vehicles from vehicle generators
-  limits spawning to outside of the view near the player (with exceptions)
Fixes #16 
Issues:
=> Parked traffic and out-of-view spawning

rwengine/include/objects/VehicleObject.hpp, rwengine/src/objects/CharacterObject.cpp, rwengine/src/objects/VehicleObject.cpp, rwengine/src/script/modules/GameModule.cpp, rwengine/src/script/modules/ObjectModule.cpp, rwengine/src/script/modules/VMModule.cpp
This implements (stubs) the 'Taxi Driver' mission.
---
To test this, go to the last island (teleport to airport for example), enter a taxi, drive near passengers and press "Shift" (or whatever your Sprint key is)
---
**Known issues (all of which can be fixed after merge):**
- Peds like to spawn in very bad spots (Unrelated, this is  a problem of the traffic spawner)
- Peds are "flickering" when selecting them (probably a problem with the traffic spawner)
- Always claims you earned "$-1" (no idea why)
- Peds don't wait for your taxi and don't hail the taxi (stubbed only)
- Taxi lights stay off (stubbed only)
- Only works on last island (airport etc.) because we currently don't support the script function to check if an island is loaded
---
I intend to create an issue about the "random …
=> Stub Taxi-Mission

.gitmodules, CMakeLists.txt, cmake/external/CMakeLists.txt, cmake/external/mman-win32.cmake, rwengine/CMakeLists.txt, rwengine/include/data/ObjectData.hpp, rwengine/include/render/ViewFrustum.hpp, rwengine/include/rw_mingw.hpp, rwengine/src/ai/TrafficDirector.cpp, rwengine/src/engine/GameData.cpp, rwengine/src/engine/GameWorld.cpp, rwengine/src/engine/SaveGame.cpp, rwengine/src/render/ObjectRenderer.cpp, rwgame/CMakeLists.txt, rwgame/GameConfig.cpp, rwgame/debug/TcpSocket.cpp, rwgame/debug/TcpSocket.hpp, rwlib/source/platform/FileIndex.cpp, rwlib/source/platform/msdirent.h
Hi. I'm kinda new at all of this, so there are couple things I am not sure about. 
1) Msdirent header (how to distribute it? where should it be in the project tree?) 
2) Some defines in the windows platform headers collide with enum identifiers and class fields/members names. My approach at solving this is questionable (a header with #undef macros), but it's the only one that worked for me.
I haven't tried to build tools and tests, just rwgame/rwengine/rwlib.
=> Make rwgame build and run on windows

rwengine/include/dynamics/CollisionInstance.hpp, rwengine/include/engine/GameWorld.hpp, rwengine/include/objects/CharacterObject.hpp, rwengine/include/objects/GameObject.hpp, rwengine/include/objects/InstanceObject.hpp, rwengine/include/objects/VehicleObject.hpp, rwengine/src/ai/CharacterController.cpp, rwengine/src/dynamics/CollisionInstance.cpp, rwengine/src/engine/GameWorld.cpp, rwengine/src/objects/CharacterObject.cpp, rwengine/src/objects/GameObject.cpp, rwengine/src/objects/InstanceObject.cpp, rwengine/src/objects/VehicleObject.cpp, rwengine/src/render/ObjectRenderer.cpp, rwgame/ingamestate.cpp, tests/test_vehicle.cpp
This is a subset of changes included in #119 that aren't related to vehicles. Vehicle physics requires a bit more work so these changes can be fast-tracked since they're complete.
- Remove defunct code
- Use bullet motion states to update object transformations
- make getPosition/getRotation non-virtual 
- Instances (lamposts, boxes etc) will now move along with their rigid body
Fixes #72 (doors will be fixed in the next PR)
=> MotionStates & physics cleanup

rwengine/include/engine/GameInputState.hpp, rwengine/include/engine/GameState.hpp, rwengine/include/objects/CharacterObject.hpp, rwengine/src/objects/CharacterObject.cpp, rwgame/ingamestate.cpp, rwgame/ingamestate.hpp
This separates the SDL key bindings from the logic of those events, and also makes input state part of the engine code. This will make it easier to implement certain opcodes.
=> Seperate Input state from binding

rwengine/src/render/GameShaders.cpp, rwengine/src/render/MapRenderer.cpp, rwengine/src/render/TextRenderer.cpp
Uniform buffer objects have been [in core since 3.1](https://www.opengl.org/wiki/Uniform_Buffer_Object), and as we're currently on 3.3 there's no reason to keep these around. More importantly this extension isn't supported on Mac and will generate shader warnings.
I'm not sure whether we also need _GL_ARB_explicit_attrib_location_ -- I'm unable to find any information about its core status. It's not generating any warnings, and it does work fine without it on the Mac running Intel 4.1.
=> Remove GLSL extensions that are in core

rwgame/benchmarkstate.cpp, rwlib/source/job/WorkContext.hpp, rwviewer/views/ModelViewer.cpp
Previously the worker thread was constructed before the queue was, leading to
unfortunate race conditions. This fixes that, along with unrelated minor cleanup.
=> Fix the construction of WorkContext

.travis.yml
This causes the script tool and data viewer to be compiled on Travis CI.
This hopefully avoid breaking some of the non-game components of OpenRW in future-PRs.
It causes slight slowdowns due to the dependency on Qt which is a rather large package.
=> Travis: Build all tools

rwviewer/ViewerWidget.cpp, rwviewer/ViewerWidget.hpp, rwviewer/ViewerWindow.cpp
3 Simple changes to RWViewer:
- Init GL 3.3 core context (code stolen from Qt sample page; fixes error in GL code)
- Don't load models/txd as we might not have that file (fixes assert or crash, can't remember)
- And finally don't hog the CPU (My machine can't keep up with 16ms interval so events will stack up. When opening a file dialog this means a framerate of about 1 FPS for the entire process which makes it impossible to select files)
The last one is a bit hacky. Ideally we'd only redraw if necessary and sync to VSYNC somehow.
But: we can fix that later.
=> Fix RWViewer

CMakeLists.txt, rwgame/GameConfig.cpp
This PR lets OpenRW build on OpenBSD! Game starts and is playable!
=> add support for OpenBSD

rwengine/src/render/GameShaders.cpp
This applies the proposed patch from #160 to fix rendering on AMD GPUs.
We should document the game behaviour  then implement it properly (if this is not fixed/handled by librw). However, it should be discussed in a new issue, as it's beyond the scope of this PR.
For now it's better to have pop-in, than breaking compatibility with possible users / devs.
---
All credits to @danhedron for investigating and fixing this. I'm only doing the PR
=> Remove screen-door fade-in effect

rwengine/src/engine/GameWorld.cpp, rwengine/src/objects/VehicleInfo.hpp, rwengine/src/objects/VehicleObject.cpp
I've tested this on all cars in testmode and it worked fine.
I've only tested entering the driver seat (front left).
The motivation for storing data like this has been that we are able to find front and backseats without iterating over all available seats, while still being able to get any seat easily.
The code replaces one `at()` by `[]` and overloads an `operator[]` elsewhere without bounds checking.
This is written under the assumption that we fix those kind of issues at a later point (lint etc.) or do bounds checking elsewhere.
Fixes #73
=> Refactor seat storage, fixes entering wrong seat

CMakeLists.txt, rwengine/CMakeLists.txt, rwengine/src/data/GameTexts.cpp, rwengine/src/data/GameTexts.hpp, rwengine/src/engine/GameState.cpp, rwengine/src/engine/GameState.hpp, rwengine/src/engine/SaveGame.cpp, rwengine/src/engine/ScreenText.cpp, rwengine/src/engine/ScreenText.hpp, rwengine/src/loaders/LoaderGXT.cpp, rwengine/src/render/TextRenderer.cpp, rwengine/src/render/TextRenderer.hpp, rwengine/src/script/modules/GameModule.cpp, rwgame/CMakeLists.txt, rwgame/DrawUI.cpp, rwgame/MenuSystem.hpp, rwgame/RWGame.cpp, rwgame/states/DebugState.cpp, rwgame/states/LoadingState.cpp, rwgame/states/MenuState.cpp, rwgame/states/PauseState.cpp, tests/test_globals.hpp, tests/test_text.cpp
This fixes:
- Incorrect text handling
- Text is now stored as it is loaded from the GXT
- Glyphs are looked up in the font map using the text properly
- Not localized menu text
- Use the GXT strings for the main menu and the pause menu
- Use the correct font for the menu
- Remove iconv
=> Overhaul GXT handling and menu text

cmake/external/mman-win32.cmake, rwengine/CMakeLists.txt, rwengine/src/render/GameRenderer.cpp, rwgame/CMakeLists.txt, rwgame/DrawUI.cpp, rwgame/states/IngameState.cpp
This does some minor cleanup for MinGW to make the build process less error prone.
* I've replaced all uses of cmath as we can also use the glm constants.
* master wouldn't work when the system include path is read only as mman was installed into the system path which is a no-no anyway.
* rwengine itself depends on iconv (LoaderGXT) and mman (MADStream). While these are linked by rwgame they are also required for rwviewer (which uses rwengine, but doesn't link them = fail). This commit is a purely temporary measure (See notes below)
Ideally we'd also link to iconv from every platform, but @danhedron is working on removing iconv altogether, so it's really not that important.
I wasn't sure wether I can remove the link to mman from rwgame so I kept it for now (someone on IRC said they might …
=> Cleanup MinGW build

rwengine/src/loaders/LoaderIDE.cpp, rwengine/src/render/ObjectRenderer.cpp
This is an implementation of TOBJ support for openrw, fixing issue #219. 
So far, I don't handle breakable TOBJ objects, as I can't find any in my GTA3 files and as such I don't think support for that would be required to play GTA3. I can look into it further if needed, however.
It also seems that for static meshes that have day/night variants, only one of the two has collision information, so it seems to be purely graphical for those. If we ever have breakable TOBJ, we need to look into how the physics for those should be handled.
As I pointed out in #219, the windows near the debug spawn area all seem to be offset from their respective buildings. I have no idea what the cause of this is.
=> Fixes #219: Take TOBJ data into account when building render lists

rwengine/src/objects/InstanceObject.hpp, rwengine/src/render/ObjectRenderer.cpp, rwengine/src/script/modules/GTA3ModuleImpl.inl
Fixes #51. Only implements 0363. No known issues.
---
Style wise it's debatable wether `setVisible` should be part  of GameObject instead. It might deserve a comment about being entirely script controlled (and not something like TOBJ) but I wasn't sure what kind of doc format I should use.
I'd also prefer `args.getModel()` or an overload for `ScriptModel`, but it's beyond the scope of this PR.
---
Probably conflicts with #220 (I'll happily rebase after #220 is merged).
=> Script: Implement opcode_0363 (Object visibility)

rwgame/GameWindow.cpp, rwgame/main.cpp
This adds some usability fixes:
- Check that we actually opened a window and get a gl context
- Don't show the window if we don't get an OpenGL context
- Show an error dialog for environments where stderr is not readily accessible
=> Improve SDL & GL initialisation failure handling

rwengine/src/engine/GameState.hpp, rwengine/src/engine/GameWorld.cpp, rwengine/src/render/GameRenderer.cpp, rwengine/src/render/MapRenderer.cpp, rwengine/src/render/MapRenderer.hpp, rwengine/src/script/ScriptFunctions.hpp, rwengine/src/script/modules/GTA3ModuleImpl.inl
This fixes #61 by implementing the colored blips. Their size is also initialized correctly now.
Also blips which aren't supposed to be shown (controlled via script) are hidden too now (This does not hide the savegame icons etc. when on a mission because it's a seperate mechanism).
Not all script functions for the blips have been implemented yet. However, it's certainly better than nothing at all / white blips.
I've also changed the order the radar north and player marker are drawn so they don't draw over the blips.
---
I accidently went a little overboard and implemented triangular up/down arrows but later found out they were only introduced in vice city. So I'll keep that code to myself for now - it's not part of the PR.
I'll probably refactor the code a bit and submit a version where it …
=> Coloured radar-blips and radardisc z-order

rwgame/states/DebugState.cpp, rwgame/states/DebugState.hpp
This fixes 3 seperate issues:
- Undefined behaviour as `_invertedY` was not initialized and caused random camera inversion. This new implementation uses the user-configuration like `IngameState` does.
- Speed-modifier (`sonicSpeed`) was broken because the modifier flag was checked in key-up / down instead of checking for shift directly (which didn't work for unknown reasons?). Ideally we should check the key state instead. However, this is an okay workaround.
- The camera speed was adjusted as it was often too fast for accurate placement (it's still fast).
(I don't feel like looking into why the speed modifier didn't work. It might be a result from more than one modifier being active on XFCE. The original code should have simply AND'ed for the shift press instead or sticked to the working …
=> Fix debug-camera

rwgame/RWGame.cpp, rwgame/main.cpp
On my Fedora using the fullscreen mode permamently changes the display resolution. Obviously this is extremely inconvenient. The fix is making sure `SDL_Quit` is called before exit. This function is safe to call - even if SDL init fails.
=> Make sure SDL_Quit() is called on exit

rwengine/src/engine/GameState.hpp, rwgame/DrawUI.cpp, rwgame/RWGame.cpp, rwgame/RWGame.hpp, rwgame/states/IngameState.cpp, rwgame/states/IngameState.hpp
This implements a cheat handler.
Only a couple of cheats are actually implemented.
There will have to be some decision how we will differentiate different official R* versions of GTA3 as cheats were changed in different regions and updates. I've added some defines near the cheat handler as a temporary workaround.
This also fixes some issue with the game state which broke the "IFIWEREARICHMAN" cheat (money used to be `uint16_t` in OpenRW, and so many other values which are listed as dword on gtamodding).
As I was messing with the money values anyway I decided to improve the money display.
It's now zero-padded to 8 digits. The value also increases slowly now.
The behaviour for the [money counting was reverse engineered (from a video) and documented …
=> Cheat handler + Money display

.travis.yml, rwgame/CMakeLists.txt, rwgame/RWGame.cpp, rwgame/main.cpp
I've had a go at issue #177. It's a simple change, but there are still some points that are up for discussion.
For example, I don't fully understand each available option yet - maybe you could provide some accurate descriptions for the options with a TODO.
The most important point is how to exit when `--help` is used. In the short term an exception can be used, however it's not very clean.
In the longer term command line parsing should probably be decoupled from the SDL/engine initialization and maybe even merged with config file parsing (btw. Boost has support for that, but might not work together with the current config setup). This would require more rewriting though.
=> Parse command line arguments with Boost

rwgame/RWGame.cpp, rwgame/RWGame.hpp
There was quite a bit of cruft in the <keyboard>F1</keyboard> debug view.
- Remove not-even working values
- Move object data into its own view on F4
- Show object state for nearby objects (might be useful to check objects are in the state scripts expect)
=> Improve Debug Views

rwengine/src/objects/CharacterObject.cpp
Bullet 2.83.5 was 283, 2.83.6 was 284, 2.84 (API changes affecting OpenRW) was 285, 2.85.1 is still 285.
We want to check for 2.84 and upwards, so our check must be for 285.
Also see https://github.com/bulletphysics/bullet3/issues/854#issuecomment-258944820 (apparently 2.84 was a mistake, when really it looks like 2.83.6 was the mistake?!)
I'd like to have this tested by IRC user vincentflyson (who reported issues with the original check).
=> Fixup BT_BULLET_VERSION check

rwengine/src/engine/GameInputState.hpp, rwengine/src/engine/GameState.hpp, rwengine/src/script/modules/GTA3ModuleImpl.inl, rwgame/CMakeLists.txt, rwgame/GameInput.cpp, rwgame/GameInput.hpp, rwgame/RWGame.cpp, rwgame/states/IngameState.cpp, rwgame/states/IngameState.hpp, tests/CMakeLists.txt, tests/test_Input.cpp
- Prevent actions like jumping or entering vehicles being requested twice by checking for keypresses 
- Zero player input while it is disabled, preventing jumping in cut-scenes
- Fix aliasing of input controls
Relates to #233,  #208, #224
=> Input fixup

CMakeLists.txt, rwengine/src/audio/MADStream.hpp, rwengine/src/audio/SoundManager.hpp, rwengine/src/audio/alCheck.cpp
This PR changes how the OpenAL headers are imported, fixing a compile error on OSX. Only tested on OSX.
=> OpenAL headers, fix for OSX compile

rwengine/src/engine/GameData.cpp, rwengine/src/engine/GameData.hpp, rwengine/src/engine/GameWorld.cpp, rwengine/src/objects/PickupObject.cpp, rwengine/src/objects/ProjectileObject.cpp, rwengine/src/render/GameRenderer.cpp, rwengine/src/render/MapRenderer.cpp, rwengine/src/render/ObjectRenderer.cpp, rwengine/src/render/TextRenderer.cpp, rwengine/src/render/WaterRenderer.cpp, rwgame/DrawUI.cpp, rwlib/source/gl/TextureData.hpp, rwlib/source/loaders/LoaderDFF.cpp, rwlib/source/loaders/LoaderDFF.hpp, rwlib/source/loaders/LoaderTXD.cpp, rwlib/source/loaders/LoaderTXD.hpp
This collects textures by slot name, which keeps the textures from each TXD from conflicting.
=> Load textures into separate groups

rwgame/DrawUI.cpp
There's no game->getSecond(), so currently made it disappear once every two game-minutes, even though the vanilla engine makes it blink exactly twice in a single game-minute.
The time runs slightly faster in the original game than so I thought it's okay for now.
=> make the health indicator blink if low

rwengine/src/objects/PickupObject.cpp, rwengine/src/objects/PickupObject.hpp
Comparing to what I see in the original game, the texture for big pickups is `coronaringa` while the texture for money and perhaps some other small pickups must be `coronacircle`.
The value of the 4th parameter of glm::vec4() is being omitted by the engine at the moment and does not affect the transparency of the sprite, it seems.
Neither I could adjust the size of the corona using `m_corona->particle.size = glm::vec2(0.5f, 0.5f);`.
Possibly the scaling has not been implemented yet; investigating that was outside the scope of this PR so I've decided not to.
Here is the color table that I made based on the colors which @aap extracted from the binary:
```
ff0000 bat
00ff00 pistol
8080ff uzi
ffff00 shotgun
ff00ff ak47
00ffff m16
ff8000 sniper
00ff80 rocket
8000ff flame
80ff00 molotov
ffffff …
```
=> apply various colors to pickups' coronas, use the correct texture

rwengine/src/objects/CharacterObject.cpp, rwgame/DrawUI.cpp, rwgame/states/IngameState.cpp
The order of the weapons in the inventory seems to be a bit off comparing to vanilla.
Couldn't find where to alter that quickly and it's probably enough commits for a single PR so next time Ü
=> Fix weapon scrollback

rwengine/CMakeLists.txt, rwengine/src/ai/CharacterController.cpp, rwengine/src/data/AnimGroup.cpp, rwengine/src/data/AnimGroup.hpp, rwengine/src/engine/GameData.cpp, rwengine/src/engine/GameData.hpp, rwengine/src/objects/CharacterObject.cpp, rwengine/src/objects/CharacterObject.hpp, tests/test_character.cpp
- Refactor Animation Groups
- Add hard-coded data for each animation group
- Refactor CharacterController to remove usage of Animation* (mostly, still talks directly to Animator in a few places)
- Apply the correct animation group to every character
I don't like the hard-coded data in AnimGroup.cpp, any ideas on how that could be better written is appreciated.
=> Implement basic Anim groups

rwgame/DrawUI.cpp, rwgame/states/IngameState.cpp
Made a few more small fixes to the weapon inventory system.
The main issue that I currently see is that weapons which have clips don't get reloaded by themselves when picked up or scrolled to like in the vanilla engine. Most likely there needs to be a separate method to accomplish that which we'd call from both UseItem, onCharacterTouch and from cycleInventory.
=> More weapon scrollback fixes

rwengine/src/render/ObjectRenderer.cpp
This is my latest masterpiece.
None of Rhino's wheels change angle in vanilla. The vehicle however is able to somehow turn.
Whatever Rhino really is, tanks make turns by making continuous tracks run in opposite directions from one another. My conspiracy theory here's that's what was supposed to happen in GTA-III to allow Rhino to be more mobile and turn on the same spot.
But in the original engine Rhino has to be in motion in order to make a turn, yet all of its wheels are parallel at all times. Go figure.
This PR prevents Rhino from turning completely, but since that thing barely moves at the moment, this could be considered an improvement because the normally concealed front wheels no longer point through the sides of the vehicle whenever player presses "left" or "right" control keys.
=> Prevent Rhino's front wheels from changing steering angle

rwengine/src/ai/CharacterController.cpp, rwengine/src/objects/CharacterObject.cpp, rwengine/src/objects/CharacterObject.hpp, rwengine/src/objects/VehicleObject.cpp, rwengine/src/objects/VehicleObject.hpp
This is quite primitive yet works fine.
Somehow I've kept running into one trouble after another, spending way too much time on trying to get $25 out of cabs. There seems to be no easy way to increase the amount of money from the inside of that class.
My wild guess is that this all should be happening via OpCodes, and perhaps within some other class. Every vehicle instance should also have a flag which shows that the perk has already been collected (which gets set to true if the car got spawned out of a garage).
=> Implement in-car perks

rwengine/src/objects/VehicleObject.cpp
Glm allows to use angle manipulation functions. One of them is conversion degrees to radians.
It gives optimal precision and isn't strictly connected with float.
https://glm.g-truc.net/0.9.4/api/a00136.html#ga4fb76e28851c9ff6653532566084e091
// For mainteiners:
Please close https://github.com/rwengine/openrw/pull/295
New pull request prevents trash in history, and it's easier to read. Thx.
=> Replace manual conversion with glm's function

rwengine/src/data/CutsceneData.hpp, rwengine/src/loaders/GenericDATLoader.cpp, rwengine/src/loaders/LoaderCutsceneDAT.cpp, rwengine/src/script/modules/GTA3ModuleImpl.inl
rwengine/openrw#286 only enables building OpenRW on Windows. The generated binary does not work.
This PR fixes some blatant bugs that will solve this problem.
The Windows performance is not good, but this allows implementing Windows integration like rwengine/openrw#276
=> Fix bugs in Windows build

CMakeLists.txt, rwengine/src/TextureArchive.cpp, rwengine/src/engine/SaveGame.cpp, rwengine/src/loaders/GenericDATLoader.cpp, rwengine/src/loaders/LoaderCutsceneDAT.cpp, rwengine/src/render/OpenGLRenderer.cpp, rwgame/GameBase.cpp, rwlib/CMakeLists.txt, rwlib/source/loaders/RWBinaryStream.hpp, rwlib/source/rw/abort.cpp, rwlib/source/rw/defines.hpp
This PR adds the following feature in Debug build mode:
- `RW_ABORT` to abort the current process and jump to the debugger. Process is not resumeable.
- `RW_ASSERT` to check an assertion. Jump to the debugger if check failed. Process is not resumeable if the check failed.
- `RW_BREAKPOINT` to break the current process and jump to the debugger. The process is resumeable
- Add a CMake option to choose what to do when a check fails..
- Add a callback to `RW_ABORT` and `RW_BREAKPOINT` to ungrab the mouse. The mouse is grabbed again in RW_BREAKPOINT when continuing..
- Change all occurrences of assert to RW_ASSERT to make use of the callbacks.
This should make it easier for people to debug OpenRW in IDEs.
=> Add option to abort/break on failed checks or at request

.gitignore, rwengine/src/engine/GameData.cpp, rwengine/src/engine/ScreenText.hpp, rwengine/src/objects/CharacterObject.cpp, rwengine/src/render/ObjectRenderer.cpp, rwgame/State.cpp, rwgame/states/BenchmarkState.cpp, rwgame/states/BenchmarkState.hpp, rwgame/states/DebugState.cpp, rwgame/states/DebugState.hpp, rwgame/states/IngameState.hpp, rwlib/source/gl/gl_core_3_3.c, rwlib/source/gl/gl_core_3_3.h
Hi again!
Found an old leftover branch of mine with basic fixes for some annoying warnings when compiling with clang.
Rebased on master, though you guys could still have use for it.
Ref #59 
Cheers!
=> Fix some warnings with clang

rwengine/src/render/OpenGLRenderer.cpp, rwengine/src/render/OpenGLRenderer.hpp
This is a simple change to get some extra performance where it matters, on integrated GPUs.
- Don't request a new buffer for every draw.
- Allocate as large a buffer as possible and copy per-draw data into it sequentially until it is full, then allocate a new buffer and start over.
=> Improve rendering performance on Intel

rwengine/src/render/OpenGLRenderer.cpp
This fixes compilation macOS - it does not have mempcpy.
The return value is unused anyway, so no semantic change.
=> Use memcpy instead of (glibc-specific) mempcpy.

rwengine/src/objects/CharacterObject.cpp
Fixes #318. Tested with bullet version 2.87, ~~probably breaks older versions of bullet where the jumping was working~~.
=> Fix jumping in newer bullet version

rwgame/RWGame.cpp, rwgame/RWGame.hpp
I'm not sure, is it a solution similar to the previous one(which has been interpolating everything)? I've used this example: http://bulletphysics.org/mediawiki-1.5.8/index.php/Canonical_Game_Loop
To do:
paused.
Ref:
#297
=> Interpolation PULL for discusion

rwengine/src/engine/GameWorld.cpp
Should prevent vehicles spawning in, and falling through, the ground.
Fixes #162
=> Offset vehicle spawn height to account for dimensions

rwengine/src/render/DebugDraw.hpp, rwengine/src/render/GameRenderer.cpp, rwengine/src/render/GameRenderer.hpp, rwengine/src/render/MapRenderer.cpp, rwengine/src/render/MapRenderer.hpp, rwengine/src/render/OpenGLRenderer.cpp, rwengine/src/render/OpenGLRenderer.hpp, rwengine/src/render/TextRenderer.cpp, rwengine/src/render/TextRenderer.hpp, rwengine/src/render/WaterRenderer.cpp, rwengine/src/render/WaterRenderer.hpp, rwgame/RWGame.cpp, rwviewer/ViewerWidget.cpp
Ok, I've edited pull request, because now happens much more. ;)
I've found some problems. First OpenGL programs have never been removed/closed. So I've added code doing it (in commit 75b188f), but now destructor have never been called, because memory allocated by OpenGLShaderPrograms are handled by raw pointers and never is freed. So I converted them unique pointers(commit 30a12ea).
I also improved the management of shaders in function compileProgram(commits 86d9122, 49f38e3, c858454). It should reduce memory usage.
Template I used: 
glCreateProgram
glCreateShader
glShaderSource
glCompileShader
glAttachShader
glLinkProgram <- after this line opengl got everything it needs, you can free shader resources
glDetachShader
glDeleteShader
for{//render loop
glUseProgram
//...drawing operations …
=> Improving handling game shaders

cmake_configure.cmake, cmake_options.cmake, rwengine/src/engine/SaveGame.cpp, rwlib/CMakeLists.txt, rwlib/source/platform/FileIndex.cpp, rwlib/source/platform/FileIndex.hpp, rwlib/source/rw/filesystem.hpp, tests/test_Config.cpp
The existing filesystem usage has been adjusted to using the rwfs namespace.
The FILESYSTEM_LIBRARY option allows a choice between how the rwfs namespace will be defined:
- ___CXX17___: using the ``<filesystem>`` header & ``std::filesystem``.
- ___CXXTS___: using the ``<experimental/filesystem>`` header and ``std::experimental::filesystem``.
- ___BOOST___: using boost filesystem. The default for now as we still target C++14.
=> Add build time option for CXX17 or boost filesystem

rwengine/src/audio/SoundManager.cpp
Probably forgotten during porting ffmpeg. And probably it's last memory leak.
Ref:
https://github.com/leixiaohua1020/simplest_ffmpeg_audio_player/blob/master/simplest_ffmpeg_audio_decoder/simplest_ffmpeg_audio_decoder.cpp#L137
Btw: av_free_packet is deprecated, so I used unref. Edit. not available in travis's ffmpeg.
Btw2: If you want to test, try heaptrack it's much, much faster than valgrind. Before ~20MB leak.
=> Forgotten flush of packet

rwengine/src/render/GameRenderer.cpp
This fixes a wrong billboarding matrix for effects visible around pickups such as weapons.
=> Fix particle rendering transform matrix

cmake_configure.cmake, tests/test_Globals.hpp
Recent versions of Arch Linux and Fedora Linux bring Boost 1.65+
Boost-unit-test includes a nullptr_t specialization of the printer,
so only use it on older versions of the boost libraries.
See [this travis log](https://travis-ci.org/madebr/openrw/jobs/314980016) for the error on Arch Linux.
fixes:
error C2766: explicit specialization;
'boost::test_tools::tt_detail::print_log_value<std::nullptr_t>' has
already been defined
C:\Boost\include\boost-1_64\boost/test/tools/detail/print_helper.hpp(169):
note: see previous definition of 'print_log_value<std::nullptr_t>
=> tests: boost 1.64 has a print_log_value<nullptr_t> implementation

.travis.yml, rwlib/source/data/Clump.cpp
So, although this is again a very small PR, this contains the last remaining bits to have successful travis builds on macOS.
=> Make travis builds for macOS succeed again.

cmake_configure.cmake
In order to build OpenRW with libglm-dev version >= 0.9.9,
the flag GLM_ENABLE_EXPERIMENTAL needs to be set.
This is now done in cmake_configure.cmake , I'm not sure if it's the best spot but it works.
=> Add experimental flag needed by glm 0.9.9

rwengine/src/data/WeaponData.hpp, rwengine/src/engine/Animator.cpp, rwengine/src/engine/SaveGame.cpp, rwengine/src/objects/CharacterObject.hpp
Before: https://gist.github.com/ShFil119/85d77d2e03503db711af715d12104907
I've also changed type of inventorySlot. So it fixes that annoying warning in each travis build.  
"warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
return i.weaponId == pistol->inventorySlot;"
=> Clang double promotion warns

rwengine/src/TextureArchive.cpp, rwengine/src/core/Profiler.hpp, rwengine/src/data/ZoneData.hpp, rwengine/src/engine/GameData.cpp, rwengine/src/engine/SaveGame.cpp, rwengine/src/loaders/LoaderIDE.cpp, rwengine/src/loaders/LoaderIPL.cpp, rwengine/src/script/SCMFile.cpp, rwlib/source/data/Clump.hpp, rwlib/source/loaders/LoaderDFF.cpp
One more emplace_back and usage std::move when possible.
=> Use std::move

.travis.yml, scripts/docker/fedora_latest.docker
This fixes the fails of Fedora and Apple on ci.
=> docker: use latest branched fedora version instead of rawhide + fix mac ci

rwgame/RWGame.cpp
Fixes issue #380 
Behavior described in the above issue was not limited only to cutscenes. In any case the game was paused, it "catch" up the time it was paused after unpausing. This can be noticed most easily by checking the in-game clock before pausing the game, waiting for a while and after unpausing the game clock fast forwarded regarding the time it was paused. This PR fixes that issue.
=> Fix pausing issues

rwengine/src/render/GameRenderer.cpp, rwengine/src/render/ObjectRenderer.cpp
https://learnopengl.com/Advanced-OpenGL/Blending
suggests transparent objects should be last.
It should partially help with #258.
=> Fix order of transparent objects

CMakeLists.txt
Needed since CMake 3.11.0: CMP0072 policy
https://cmake.org/cmake/help/v3.11/policy/CMP0072.html
Silences this warning:
```
CMake Warning (dev) at /usr/share/cmake/Modules/FindOpenGL.cmake:270 (message):
Policy CMP0072 is not set: FindOpenGL prefers GLVND by default when
available.  Run "cmake --help-policy CMP0072" for policy details.  Use the
cmake_policy command to set the policy and suppress this warning.
FindOpenGL found both a legacy GL library:
OPENGL_gl_LIBRARY: /usr/lib64/libGL.so
and GLVND libraries for OpenGL and GLX:
OPENGL_opengl_LIBRARY: /usr/lib64/libOpenGL.so
OPENGL_glx_LIBRARY: /usr/lib64/libGLX.so
OpenGL_GL_PREFERENCE has not been set to "GLVND" or "LEGACY", so for
compatibility with CMake 3.10 and below the legacy GL library will be used.
Call Stack (most recent call …
```
=> cmake: use OpenGL GLVND libraries by default

rwengine/src/engine/GameState.hpp, rwengine/src/script/ScriptFunctions.hpp, rwengine/src/script/modules/GTA3Module.cpp, rwengine/src/script/modules/GTA3ModuleImpl.inl
=> Implemented blip opcodes

rwengine/src/render/GameRenderer.cpp, rwengine/src/render/MapRenderer.cpp, rwengine/src/render/ObjectRenderer.cpp, rwengine/src/render/OpenGLRenderer.cpp, rwengine/src/render/OpenGLRenderer.hpp, rwengine/src/render/TextRenderer.cpp
It seems code of changing weapon corona color in master written to use additive blending
<p><details><summary>Also in GTA 3 and VC(at least in VC) using additive blending for weapon coronas(clickable)</summary><p>
---
So there is a directx code that i got with MS PIX(part of directx sdk):
As you can see GTA VC is using additive blending
Also you might notice that in one moment corona look the same as in GTA 3, so we can make a conclusion that in it used almost the same render code:
[Here](http://www.mediafire.com/file/f38uonxzkr8c3bj/VC.PIXRun) is output of PIX for more detail researching
Also I tried to do the same for GTA 3 but all my tries(I tried to use MS PIX and apitrace) were unsuccessful
---
</p></details></p>
So I added choosing of blending mode in setBlend and DisplayParameters: …
=> Added transparency for pickups

rwengine/src/script/modules/GTA3ModuleImpl.inl
=> [Ready] Implemented some locate opcodes

rwengine/src/objects/CharacterObject.cpp, rwengine/src/objects/VehicleObject.cpp, rwengine/src/objects/VehicleObject.hpp, rwengine/src/script/modules/GTA3ModuleImpl.inl
Minor changes, but this should make more missions playable, because now it's possible to "destroy" vehicles.
=> [Ready] Vehicle health

rwengine/src/ai/PlayerController.cpp, rwengine/src/ai/PlayerController.hpp, rwengine/src/engine/GameState.cpp, rwengine/src/engine/GameState.hpp, rwengine/src/objects/CharacterObject.cpp, rwengine/src/objects/CharacterObject.hpp, rwengine/src/script/modules/GTA3ModuleImpl.inl
Respawning is now handled, related opcodes seemed to work.
Closes #48
=> [Ready] Respawn functionality

.travis.yml
There's problem of two dependency systems. (pip2 and brew)
Easiest way to fix is to remove pip2's  numpy before upgrading python.
Ref:
https://github.com/travis-ci/travis-ci/issues/6688
=> Fix mac build

rwgame/GameBase.cpp, rwgame/GameConfig.cpp, rwgame/GameConfig.hpp
As the configuration of OpenRW is rather basic, this commit extends the configuration file with a **[window]** section. It is now possible to set the **width** and **height** of the window and choose whether it should start in **fullscreen**.
This is the content of my openrw.ini file:
```
[game]
path=/path/to/game/data/
language=american
[input]
invert_y=0
[window]
width=1920
height=1080
fullscreen=0
```
=> Added window configs

rwengine/src/engine/GameData.cpp, rwengine/src/engine/GameData.hpp, rwgame/RWGame.cpp
It seems like that texture for ZoneCylinder loaded correctly but `texturelookup ` can't find texture because wrong texture slot is set. So in `loadClump` we should set it manually
=> Fixed loading ZoneCylinder texture

rwengine/src/objects/InstanceObject.cpp, rwengine/src/objects/InstanceObject.hpp, rwengine/src/render/ObjectRenderer.cpp, rwengine/src/script/modules/GTA3ModuleImpl.inl
This fixes issue when during the game intro few objects fall through the ground.
Issues to fix:
=> [Ready] Fixed script objects falling through the ground

rwengine/CMakeLists.txt, rwengine/src/data/ModelData.hpp, rwengine/src/engine/GameState.hpp, rwengine/src/engine/GameWorld.cpp, rwengine/src/engine/GameWorld.hpp, rwengine/src/engine/GarageController.cpp, rwengine/src/engine/GarageController.hpp, rwengine/src/engine/SaveGame.cpp, rwengine/src/objects/InstanceObject.cpp, rwengine/src/script/modules/GTA3ModuleImpl.inl, rwgame/RWGame.cpp
This PR todo list:
---
Garages todo overall:
=> [Ready] Garages

rwengine/src/render/TextRenderer.cpp
Default text background height is 0 and it changes only if text contains 2 or more line of text. So if text contain only one line then background height will be too small
After fix:
=> Fixed one line help messages background too small

rwengine/src/render/GameRenderer.cpp
Fixes if fade duration is 0, then set alpha channel to max/min respectively
=> [Ready] Fade fix

CMakeLists.txt, cmake/modules/FindClangTidy.cmake, cmake_configure.cmake, cmake_options.cmake
This PR adds the clang-tidy linter to openrw.
All clang-tidy checks are enabled by default.
See http://clang.llvm.org/extra/clang-tidy/
Enabling clang-tidy autofix might result in incorrect source code, so manual checking is required.
=> Add clang-tidy support

rwengine/src/engine/GameState.hpp, rwengine/src/script/modules/GTA3ModuleImpl.inl, rwgame/DrawUI.cpp, rwgame/RWGame.cpp
=> Implement script timer

rwengine/src/engine/GameState.cpp
Should be `0` is `false`.
UBsan says:
`/home/filip/Projekty/bullet/openrw/fix/openrw/rwengine/src/engine/GameState.hpp:248:7: runtime error: load of value 64, which is not a valid value for type 'bool'`
=> Fix UB in gamestate

rwengine/src/objects/CharacterObject.cpp
Fixes this warning:
```
/home/maarten/programming/openrw/rwengine/src/objects/CharacterObject.cpp:202:54: runtime error: downcast of address 0x00000ae11d00 which does not point to an object of type 'PlayerController'
0x00000ae11d00: note: object is of type 'DefaultAIController'
00 00 00 00  58 91 ca 00 00 00 00 00  e0 2e 90 0b 00 00 00 00  00 00 00 00 00 00 00 00  00 00 00 00
^~~~~~~~~~~~~~~~~~~~~~~
vptr for 'DefaultAIController'
/home/maarten/programming/openrw/rwengine/src/objects/CharacterObject.cpp:202:75: runtime error: member call on address 0x00000ae11d00 which does not point to an object of type 'PlayerController'
0x00000ae11d00: note: object is of type 'DefaultAIController'
00 00 00 00  58 91 ca 00 00 00 00 00  e0 2e 90 0b 00 00 00 00  00 00 00 00 00 00 00 00  00 00 00 00 …
```
=> rwgame: remove undefined behavior in CharacterObjects

cmake/ctest/build.ctest
This pr is partly untested because I have yet to have a cdash submission failure
=> ctest: increase the retry count for cdash test submissions

rwengine/src/script/ScriptTypes.cpp
Payphone pool is empty while ScriptPayphone object is getting unpacked during payphone creation caused out of range panic
master was broken by #498
=> Fix panic on new game 

rwengine/src/objects/VehicleObject.cpp
Hello, this is my first attempt at PR to this repo. Feel free to throw criticism at me :)
EDIT:
Unlike in vanilla engine, the vehicle wheels instantly turned to their limit angle when the player steered. I corrected this by smoothly changing the angle in each physics tick, independently of framerate. It's not just a change of animation but actual physics behavior that allows for finer steering.
=> Make vehicle wheels steer smoothly

.appveyor.yml
Fixes this: https://ci.appveyor.com/project/danhedron/openrw/build/1.0.499#L1722
Race condition:
- user1 pushes a commit to github branch `bbb` named `xxx`(=`APPVEYOR_REPO_COMMIT`)
- appveyor gets notified by github that a new commit named `xxx` is available
- appveyor fetches `.appveyor.yml`
- user1 pushes a new commit to github branch `bbb` named `yyy`
- appveyor wants to build `xxx`. Between the `init` steps and the `install` steps, appveyor fetches the repo with the commands
```
git clone -q --depth=1 https://github.com/rwengine/openrw.git C:\projects\openrw
git fetch -q origin +refs/pull/420/merge:
git checkout -qf FETCH_HEAD
```
- so now appveyor thinks it is testing commit `xxx` but has actually checked out commit `yyy`
Fixes this by not using `APPVEYOR_REPO_COMMIT` (=`xxx`)
Also, …
=> ci: use hash of checked out git repo instead of appveyor hash

rwengine/src/script/modules/GTA3ModuleImpl.inl
Fixes duped cars and peds in first mission only if you skip cutscene. Watching whole intro movie still creates duplicates.
=> Temporary partial fix for duped cars & peds in first mission

rwengine/src/engine/SaveGame.cpp, rwgame/states/DebugState.cpp
=> Fix: terminate only mission scripts when starting new mission via debug menu

rwengine/src/engine/GameState.hpp, rwengine/src/engine/GameWorld.cpp, rwengine/src/objects/PickupObject.cpp, rwengine/src/objects/PickupObject.hpp, rwengine/src/script/modules/GTA3ModuleImpl.inl, rwgame/RWGame.cpp, tests/test_Pickup.cpp
=> Big'N'Veiny pickups

CMakeLists.txt
OpenRW uses OpenGL::GL imported targets that introduced in CMake 3.8, so we [need](https://github.com/rwengine/openrw/issues/544#issuecomment-403313168) to update `cmake_minimum_required` to 3.8.
Also as said @madebr in IRC the findBoost package also has imported targets since that cmake version.
For Debian Stretch users:
In Debian repositories cmake version still lower than 3.8, so to build OpenRW you will [need](https://github.com/rwengine/openrw/issues/544#issuecomment-403395680) to install newer version of cmake from stretch-backports
=> Update cmake minimum required version to 3.8

cmake/modules/FindFFmpeg.cmake, rwengine/src/audio/SoundManager.cpp
Commit fixes #458.
It also loosens the connection
between decoder and player (openAL).
It allows to easier replace
player if there's need.
To do later:
IIRC @madebr has said something about using rwfs?
=> Usage of resampler for sounds

tests/test_Character.cpp
Actually GoTo ignores z axis (up), looks position which is targeted by is some kind of hole or slope.
And z axis is included (wrongly) into calculation of distance. So input data is ok.
Example log of character's position in test: https://gist.github.com/ShFil119/cb21d8d34ad1593c24493fa49b47c19d
Increasing time for activity is causing that z value goes into negative values.
fixes #459
=> Fix data test `test_activities`

rwengine/src/audio/SoundManager.cpp
When I was working on resampling, pull with paths was merged. It's funny how macro hides the problem. It shouldn't even compile.
=> Quick Fix filename -> filePath

.appveyor.yml
Don't fail appveyor ci build when git hashes do not match.
This happens on the first build of a pull request.
=> ci: echo APPVEYOR_REPO_COMMIT and COMMIT_HASH + do not exit on mismatch

rwengine/src/loaders/LoaderIDE.cpp, rwengine/src/loaders/LoaderIPL.cpp
It is deprecated in c++11, and removed in c++17. (It also breaks compilation on MSVC with c++17)
=> Replace std::ptr_fun with lambda

rwengine/src/data/ModelData.hpp, rwengine/src/loaders/LoaderIDE.cpp, rwengine/src/loaders/LoaderIDE.hpp, rwlib/source/rw/casts.hpp, tests/CMakeLists.txt, tests/test_LoaderIDE.cpp, tests/test_ObjectData.cpp
Part of a series to deal with #126 
This PR does the following:
- Renames ObjectDataTests to LoaderIDETests
- Makes the tests against LoaderIDE more descriptive
- Removes the dependency on game data for LoaderIDE tests
- Fixes a bug where carmask was loaded as base 10 instead of base 16
Data Free Tests: +4
Remaining issues:
=> Remove data dependency from LoaderIDE test suite

rwengine/src/engine/GameData.cpp, rwengine/src/engine/GameWorld.cpp, rwengine/src/loaders/LoaderCutsceneDAT.cpp, rwengine/src/loaders/LoaderCutsceneDAT.hpp, rwengine/src/loaders/LoaderGXT.cpp, rwengine/src/loaders/LoaderGXT.hpp, rwlib/source/loaders/LoaderDFF.cpp, rwlib/source/loaders/LoaderDFF.hpp, rwlib/source/loaders/LoaderIMG.cpp, rwlib/source/loaders/LoaderIMG.hpp, rwlib/source/loaders/LoaderTXD.cpp, rwlib/source/loaders/LoaderTXD.hpp, rwlib/source/platform/FileHandle.hpp, rwlib/source/platform/FileIndex.cpp, rwlib/source/platform/FileIndex.hpp, rwlib/source/rw/forward.hpp, rwviewer/views/ModelViewer.cpp, rwviewer/views/TextViewer.cpp, tests/test_Cutscene.cpp, tests/test_FileIndex.cpp, tests/test_LoaderDFF.cpp, tests/test_RWBStream.cpp, tests/test_Text.cpp
Been trying to convert shared_ptr to unique_ptr, but sometimes even there's no need for pointers.
Tested with address sanitizers in game, but brakes one data test:
https://gist.github.com/ShFil119/c82d46c5f548a5fd97d50194749c7770
(not sure how to fix/refactor it)
Edit:
Fixed
=> Remove unneeded FileHandle (aka shared_ptr)

CMakeLists.txt, cmake_options.cmake, conanfile.py, rwengine/src/render/TextRenderer.cpp, rwengine/src/render/TextRenderer.hpp, rwlib/source/fonts/FontMapGta3.cpp, rwtools/CMakeLists.txt, rwtools/rwfont/CMakeLists.txt, rwtools/rwfont/rwfontmap.cpp, rwviewer/views/TextViewer.cpp
- This pr adds kerning depending on the used font. Every glyph has a fixed offset assigned to it with which the text cursor moves.
These values are based on reverse engineering by jayfoxrox and aap but modified by me to look good.
- I've also taken the opportunity to code a tool that can generate new font maps. This can be useful when no game data is available.
- added fix to rwviewer: '~' characters were not visible (=color modifiers)
- fixed crash of rwviewer/rwgame when a incomplete markup string would be passed for rendering: "~g" crashes rwviewer
original pr at madebr/openrw#2
I've used this [script](https://gist.github.com/madebr/3216e7ff23701caffc25a8925570c0e1) to optimize the offsets of the fonts.
---
Example usage of the `rwfontmap` tool:
```
$ ./rwfontmap -w 1024 -h 1024 -r …
```
=> Add font-dependent kerning 

rwengine/src/loaders/LoaderIPL.cpp, rwengine/src/loaders/LoaderIPL.hpp, tests/test_LoaderIPL.cpp
This one is straightforward.
- Remove dependency on game data for LoaderIPL test suite.
- Add additional tests for instance data loading.
Changes to do:
=> Remove data dependency from LoaderIPL tests

rwengine/src/script/modules/GTA3ModuleImpl.inl
https://github.com/Lighnat0r/GTA-III-SCM-Converted/blob/master/02_wanted.sc
As you can see there's no another cleaning functionality, so 03e5 should clean after itself.
Before:
After:
How to test? Just start mission "wanted".
fixes #584
=> Fix opcode 03e5

tests/test_GameData.cpp
By fetching the paths of the sfx file in the `SoundManager` constructor, `GameWorld` needs a loaded GameData object.
This fixes the first `GameDataTests`
GameWorld -> SoundManager -> FileIndex
=> tests: GameWorld needs a loaded GameData

rwengine/src/render/GameRenderer.cpp, rwengine/src/render/GameRenderer.hpp, rwengine/src/render/OpenGLRenderer.cpp, rwengine/src/render/OpenGLRenderer.hpp, rwengine/src/render/TextRenderer.cpp
This is just an initial pass to take care of the OpenGL usage that was interfering with removing OpenGL from elsewhere, and make the code easier to look at.
- Remove unused code
- Remove bare glDraw calls
- Remove unused opengl objects
- Refactored some code into more readable methods
Follow up work:
- Remove raw OpenGL from MapRenderer
=> Cleanup Game Renderer

rwviewer/ViewerWindow.cpp
Load GameData before passing it to GameWorld.
GameWorld needs loaded GameData because SoundManager's constructor accesses it.
=> rwviewer: load gamedata before passing it to gameworld

rwengine/src/audio/SoundBuffer.cpp, rwengine/src/audio/SoundBuffer.hpp, rwengine/src/audio/SoundManager.cpp, rwengine/src/audio/SoundManager.hpp
OpenAL printing
```
AL lib: (WW) FreeContext: (0x614000052440) Deleting 22 Sources
AL lib: (WW) FreeDevice: (0x62d0001f4400) Deleting 22 Buffers
```
at program shutdown is actually a warning that not all sources and
buffers were deleted.
=> rwengine: delete OpenAL buffers and sources before OpenAL shutdown

scripts/conan/create_vs_solution.py
Python complains because of unexpected keyword argument ``remote``. It is actually ``remote_name`` in the current version of Conan API:
- https://github.com/conan-io/conan/blob/develop/conans/client/conan_api.py
The script now uses positional arguments, except when keyword argument is necessary.
=> Fix conan script error due to conan API change

rwengine/src/ai/PlayerController.cpp
Fixes #568. Jump action only checks for "not in water" condition, adding "on ground" check fixes the issue.
=> Ignore jump input while in airborne state

rwengine/src/ai/TrafficDirector.cpp, rwengine/src/objects/CharacterObject.cpp, rwengine/src/objects/CharacterObject.hpp, rwengine/src/objects/GameObject.hpp, rwengine/src/objects/VehicleObject.cpp, rwengine/src/objects/VehicleObject.hpp, rwengine/src/script/ScriptFunctions.hpp, rwengine/src/script/modules/GTA3ModuleImpl.inl
Successor of #585
The main idea is to apply the offset depending of the distance from the center of an object to its base.
This is necessary in opcodes where the coordinates refer to the position on the ground.
Until now the same offset `kSpawnOffset` was used for all objects, which isn't ideal.
While the original game uses the distance from the `CModelInfo` this isn't possible for us, as we are missing them and `CharacterObject` uses a `btCapsuleShape` as hitbox.
My idea was to implement `applyOffset()` which moves the object for the correct distance, every object can override `getCenterOffset()` to set its own value.
**Changes:**
- Pedestrians don't "jump" anymore when reaching an `AIGraphNode`
- Vehicles now spawn directly on the ground, independent of size
Changes were tested during …
=> Rewrite how offsets are applied

rwengine/src/ai/AIGraph.cpp, rwengine/src/ai/AIGraph.hpp, rwengine/src/ai/DefaultAIController.cpp, rwengine/src/engine/GameWorld.cpp, rwengine/src/objects/CharacterObject.cpp, rwgame/RWGame.cpp
Additionally avoided copying vector in `resetToAINode` and added `const` in range loops.
Refs: #598
=> Convert nodes to unique ptrs

rwengine/src/engine/GameWorld.cpp
Old version (needlessly) iterates on all objects of vector.
=> Improved function for destroying effects

rwengine/src/engine/GameWorld.cpp
Fixes #583 
I tested only the cutscene on the first mission (Luigi's Girls), but it should work for any other.
=> Pause all other sounds during a cutscene

rwengine/src/engine/GameWorld.cpp
This causes a drop from 6.5ms to 4.2ms on my machine.
Thanks to @FP4 for pointing this out in #622.
To Check:
=> setForcedUpdateAllAabbs to false; Reduces stepSimulation time by 35%.

rwengine/src/ai/CharacterController.cpp, rwengine/src/data/WeaponData.hpp, rwengine/src/engine/GameWorld.cpp, rwengine/src/items/Weapon.cpp, rwengine/src/items/Weapon.hpp, rwengine/src/objects/CharacterObject.cpp, rwengine/src/objects/CharacterObject.hpp, rwengine/src/objects/GameObject.hpp, rwengine/src/objects/ProjectileObject.cpp, rwgame/states/DebugState.cpp, tests/test_Character.cpp, tests/test_Weapon.cpp
Provide a basic implementation of melee attacks. This enables attacking while unarmed and with the bat. The alternate ground attack animation is selected if there is anyone on the ground. Currently only dead NPCs fall the ground however so this isn't all that useful yet.
=> Melee Weapon implementation

scripts/docker/arch_latest.docker
https://hub.docker.com/r/base/archlinux is deprecated
=> Update docker image

rwengine/src/render/OpenGLRenderer.cpp
When for some reason a shader object creation returns 0 then there likely will be an error when trying to allocate **sourceBuff** object (because glGetShaderiv with GL_SHADER_SOURCE_LENGTH will fail).
That cause a std::bad_alloc exception and a termination of the program. So I added a check for a shader object creation and now there will be an error message box containing clear message of what was happened.
=> Fix segfault when failed to create shader object

rwengine/src/engine/GameWorld.cpp, rwengine/src/engine/GameWorld.hpp, rwengine/src/objects/GameObject.hpp, rwengine/src/objects/VehicleObject.cpp, rwengine/src/objects/VehicleObject.hpp, rwengine/src/script/ScriptFunctions.hpp, rwengine/src/script/modules/GTA3ModuleImpl.inl
Unreferenced objects should be erased if a script is creating an object that would intersect with it.
This fixes the current issue with the intro where 8-ball and the Kuruma are duplicated.
=> Remove existing vehicles & peds when creating script objects

rwcore/data/Clump.cpp, rwcore/data/Clump.hpp, rwengine/src/dynamics/CollisionInstance.cpp, rwengine/src/dynamics/CollisionInstance.hpp, rwengine/src/engine/GameWorld.cpp, rwengine/src/engine/Garage.cpp, rwengine/src/engine/Payphone.cpp, rwengine/src/objects/CharacterObject.cpp, rwengine/src/objects/CharacterObject.hpp, rwengine/src/objects/CutsceneObject.cpp, rwengine/src/objects/CutsceneObject.hpp, rwengine/src/objects/GameObject.cpp, rwengine/src/objects/GameObject.hpp, rwengine/src/objects/InstanceObject.cpp, rwengine/src/objects/InstanceObject.hpp, rwengine/src/objects/PickupObject.cpp, rwengine/src/objects/ProjectileObject.cpp, rwengine/src/objects/ProjectileObject.hpp, rwengine/src/objects/VehicleObject.cpp, rwengine/src/objects/VehicleObject.hpp, rwengine/src/render/GameRenderer.cpp, rwengine/src/render/ObjectRenderer.cpp, rwengine/src/script/ScriptFunctions.hpp, rwengine/src/script/modules/GTA3ModuleImpl.inl, rwgame/RWGame.cpp, rwgame/states/IngameState.cpp, rwviewer/ViewerWidget.cpp, tests/test_Character.cpp, tests/test_Vehicle.cpp, tests/test_Weapon.cpp
- GameObjects now have either an Atomic or a Clump
- The transform of this object is updated to reflect where the object should be
- Accidentally fixed the player having the wrong model in the intro
=> Cleanup Atomic & Clump usage

rwengine/CMakeLists.txt, rwengine/src/audio/Sound.cpp, rwengine/src/audio/Sound.hpp, rwengine/src/audio/SoundBuffer.cpp, rwengine/src/audio/SoundBuffer.hpp, rwengine/src/audio/SoundBufferStreamed.cpp, rwengine/src/audio/SoundBufferStreamed.hpp, rwengine/src/audio/SoundManager.cpp, rwengine/src/audio/SoundManager.hpp, rwengine/src/audio/SoundSource.cpp, rwengine/src/audio/SoundSource.hpp, tests/test_AudioLoading.cpp
To think about:
```
OpenAL error at ../rwengine/src/audio/SoundBufferStreamed.cpp:22: Invalid value!
OpenAL error at ../rwengine/src/audio/SoundBufferStreamed.cpp:23: Invalid operation!
```
=> Streaming audio files

.gitmodules, cmake_options.cmake, external/CMakeLists.txt, external/imgui/CMakeLists.txt, external/imgui/rw_imconfig.h, rwengine/src/render/ViewCamera.hpp, rwengine/src/render/ViewFrustum.cpp, rwengine/src/render/ViewFrustum.hpp, rwgame/CMakeLists.txt, rwgame/GameBase.cpp, rwgame/GameWindow.hpp, rwgame/RWGame.cpp, rwgame/RWGame.hpp, rwgame/RWImGui.cpp, rwgame/RWImGui.hpp, rwgame/states/DebugState.cpp, rwgame/states/DebugState.hpp, rwgame/states/LoadingState.cpp, tests/CMakeLists.txt, tests/main.cpp, tests/test_Globals.hpp, tests/test_ViewCamera.cpp
To simplify the code (and make it nicer to use)
- cherry-pick some commits from @madebr which adds ImGui
- Replace the debug view modes with ImGui windows
- Replace the debug tools menu with ImGui
Long-term, with imgui we can:-
- Provide a bootstrap phase to input game path, if we can't auto-detect it.
- Replace rwviewer with a lighter-weight in-game version.
=> Use ImGui for debugging

cmake/modules/FindFFmpeg.cmake
Fix regex to detect the "4.2.2-1+b1" version currently available on
Debian testing.
Signed-off-by: Paul Cercueil <paul@crapouillou.net>
=> cmake: FFmpeg: Fix regex for version detection

cmake/modules/FindSDL2.cmake
We are looking for the SDL.h file inside a SDL2 folder located in the
standard include paths, so the path suffix should be simply SDL2.
The /usr/local/include/SDL2 and /usr/include/SDL2 are standard paths
with the SDL2 suffix, so they can be dropped.
Signed-off-by: Paul Cercueil <paul@crapouillou.net>
=> cmake: SDL2: Fix SDL2 headers detection

rwengine/src/audio/SoundSource.hpp
Fix build on Debian testing by adding a missing <vector> include.
Signed-off-by: Paul Cercueil <paul@crapouillou.net>
=> audio/SoundSource.hpp: Add missing include

rwcore/loaders/LoaderIMG.cpp, rwcore/loaders/LoaderIMG.hpp, rwcore/platform/FileIndex.cpp, rwcore/platform/FileIndex.hpp, rwengine/src/engine/GameData.cpp, rwengine/src/engine/GameData.hpp, rwgame/RWGame.cpp, rwviewer/models/IMGArchiveModel.hpp
Hi again!
So while working on openrw/debugging an issue, I really started to notice the significant loading time until being in-game.
I did some perf'ing and noticed that `LoaderIMG::load` was a pretty hot path and after digging a bit, I found out that `LoaderIMG::load` was called 3237(!) times with `models/gta3.img`.
That meant opening and reading the file and allocating memory for it each call.
I did some simple optimization, now each file is only loaded once by `LoaderIMG`, which resulted in a pretty nifty speedup. 
Also after these changes, `LoaderIMG::load` completely vanishes from the flamegraph.
On a hot file cache, loading on startup takes ~7600ms on `master` on my machine, after the changes it goes down to ~5100ms.
There might be even more loading time reduction on slower systems …
=> Improve file loading for .img files.

rwengine/src/audio/SoundSource.cpp, rwengine/src/audio/SoundSource.hpp
Fixes `Error: assigning to 'AVCodec *' from 'const AVCodec *' discards qualifiers`.
Building on macOS Sonoma 14.1 (23B74), using a M2 Max in an `arch -x86_64 zsh` environment.
Fixes the error by using the auto keyword to infer the correct type.
It should be noted that this *might* not be the best way to handle this. Indeed right after this, the compiler notes that the `codec` variable is never actually used in either location. Perhaps the author of the [original commit for this line](https://github.com/rwengine/openrw/commit/50c6eedf4f48bcbf749f7e0bc50b42be33c0e345), Filip Gawin, could explain what the intention was with this line. Removing this line completely also fixes the error, but I'm unable to tell if it has side effects.
=> Fixes compatibility with newer ffmpeg versions.
