.clang-format
CMakeLists.txt
rwgame/GameConfig.cpp

Reworked my changes to add GLM under macOS and included the changes  of @christoph-heiss.

more changes to compile under macOS 

---

rwengine/src/engine/SaveGame.cpp

This creates object instances from the savegame (such as doors etc.)
I couldn't confirm that the `down` vector is correct.
All objects in the savegames I have use (normalized) { 0.0, 0.0, -1.0 } as `down`.
I don't have a system capable of running GTA3 to test different matrices.
---
I think we somehow have to link these object instances to script variables, however, I'm not sure how the game manages to do that.
As far as I can remember all unknown fields are the same for some objects so it can't be stored in Block4?!

Create object instances from savegame

---

rwengine/include/objects/GameObject.hpp
rwengine/src/objects/GameObject.cpp
rwengine/src/script/modules/GameModule.cpp
rwengine/src/script/modules/ObjectModule.cpp
rwengine/src/script/modules/VMModule.cpp

This adds the missing functionality for LUIGI3 + tiny printf bugfix.
There are still some known issues:
- The doors to Mistys house do not open properly when loaded from savegame (even with #98 )
I did not test wether this works when the objects are created from the Script. It's very possible that the game currently rotates some random object, thinking that it is the door to Mistys place.
- Once Misty is in the car you can't leave it. Leaving the car [will ASSERT and SIGSEGV here](https://github.com/rwengine/openrw/blob/5628f6ceb9288716fe5b75ae7e4935d877972240/rwengine/src/script/modules/ObjectModule.cpp#L366) (not 100% sure it was this line, better confirm seperately!)
- Once the mission has passed (= after "Mission Passed" text) the camera didn't reset and I didn't get control back
- …

Partially fix LUIGI3 (Drive Misty For Me)

---

rwengine/src/script/modules/GameModule.cpp
rwengine/src/script/modules/ObjectModule.cpp
rwgame/debugstate.cpp

This fixes the mission LUIGI2 ("Don't spank my bitch up").
I consider it merge ready.
There are still a couple of known issues.
- You can't fail the mission (flipping the car crashes something in bullet, unrelated to this PR)
- You need a gun (and a mouse wheel to select it) or projectile to shoot/kill the dealer
- One of the cylinders / sphere marker thingies is not rendered as far as I know (only stubbed)
- The garage doors don't open (unrelated, see #107 ) so you need to use the debug menu for that
- Pay'n'Spray doesn't actually respray you and you only have to drive into the garage
- Once you complete the mission the car is just removed and you are suddenly on foot
---
This mostly stubs functionality.
However, it also does fix broken spawning behaviour:
`master` attempts to replace …

Fix LUIGI2

---

rwengine/include/ai/CharacterController.hpp
rwengine/include/objects/CharacterObject.hpp
rwengine/src/ai/CharacterController.cpp
rwengine/src/objects/CharacterObject.cpp

This change adds the ability to forcibly eject characters from vehicles.

Implement stealing vehicle

---

rwengine/src/script/modules/GameModule.cpp
rwengine/src/script/modules/ObjectModule.cpp

This partially fixes the mission LUIGI4 (Pump Action Pimp).
I consider it merge-ready.
I've had success finishing this mission by throwing grenades and molotov cocktails at the car.
(The car will disappear, the 2 gang members will die)
This is also affected by #132 which makes it impossible to enable 03DD (which was not tested because of that).
---
This is mostly stubbed. The car won't drive, gang members won't fight back.

Partially Fix LUIGI4

---

rwgame/debugstate.cpp
rwgame/debugstate.hpp
rwgame/menustate.cpp

Adds hierarchy to the debug menu making it easier to navigate.

UI Improvements

---

rwgame/MenuSystem.hpp
rwgame/debugstate.cpp
rwgame/debugstate.hpp
rwgame/ingamestate.cpp
rwlib/source/rw/defines.hpp

Also:
- Fix camera for tall vehicles being too high
- Debug menu additions
- Add Weapon debug menu for weapons
- Add kill all peds
- Add wrap-around to the menu system

Minor Improvements: Missing space, debug menu addition & cleanup

---

CMakeLists.txt

This only covers Linux and FreeBSD.
Anyone who knows what the right thing to do for windows and macOS is invited to tell me what to do.

Copy License to install

---

rwengine/src/ai/CharacterController.cpp
rwengine/src/objects/CharacterObject.cpp

- Don't crash if the seat doesn't have a door
- Make RHS animations count as entering or exiting animations

Fix entering & exiting vehicle animations

---

rwengine/src/engine/GameState.hpp
rwengine/src/objects/VehicleObject.hpp
rwengine/src/render/GameRenderer.hpp
rwengine/src/render/OpenGLRenderer.hpp

This fixes most of the annoying warnings.
Please have a look especially at commit 95a7e73a2af7e909c6e60e02dfb80549eaf60cd8, as I'm not sure if this is the best solution for this problem.

Some more cleanups

---

rwengine/src/engine/GameWorld.cpp
rwengine/src/engine/GameWorld.hpp
rwgame/RWGame.cpp
tests/test_GameWorld.cpp

...and make the time-cheaty debug keys not under/overflow the clock.

Add method to modify game time properly

---

README.md

Handles #200 
This just adds a list of operating systems that are supported so people know it's worth trying out. People who are interested will come across the minimum requirements while looking at the FAQ.

Update readme with the supported systems

---

rwengine/src/engine/GameData.cpp
rwengine/src/engine/GameData.hpp
rwengine/src/engine/GameWorld.cpp
rwgame/RWGame.cpp
rwgame/states/IngameState.cpp
rwgame/states/LoadingState.cpp
rwlib/source/platform/FileHandle.hpp
rwlib/source/platform/FileIndex.cpp
rwlib/source/platform/FileIndex.hpp
rwviewer/ViewerWindow.cpp
rwviewer/views/ObjectViewer.cpp
tests/test_FileIndex.cpp
tests/test_GameData.cpp
tests/test_cutscene.cpp
tests/test_globals.hpp
tests/test_loaderdff.cpp
tests/test_rwbstream.cpp
tests/test_text.cpp

This fixes the following:
- style fixes & better indentation
- Improve some naming
- Implement case-insensitive lookup of files in the game directory
- Load files from explicit paths instead of finding them using just their filename
- Remove some dead code
- Load IDE files at the correct time

Improved file handling for un-archived files

---

rwengine/src/engine/GameData.cpp
rwengine/src/engine/SaveGame.cpp
rwlib/source/loaders/RWBinaryStream.hpp
rwlib/source/platform/FileIndex.cpp
rwlib/source/platform/FileIndex.hpp

Signed-off-by: PerikiyoXD <perikiyoxd@gmail.com>

Fixed .native() and some cast errors

---

rwengine/src/objects/CharacterObject.cpp

I don't have GTA3 or OpenGL 3.3 at the moment, so I can't test.
This is enough to make it compile on Arch Linux though.
This is the commit which made this change necessary: https://github.com/bulletphysics/bullet3/commit/626a913866158e5956cfa2ae7f5f6350e99d783e

Adapt for Bullet >= 2.84

---

rwengine/src/data/CollisionModel.hpp
rwengine/src/data/ModelData.hpp
rwengine/src/dynamics/CollisionInstance.cpp
rwengine/src/dynamics/CollisionInstance.hpp
rwengine/src/engine/GameData.cpp
rwengine/src/engine/GameData.hpp
rwengine/src/loaders/LoaderCOL.cpp
rwengine/src/loaders/LoaderCOL.hpp
rwengine/src/objects/InstanceObject.cpp
rwengine/src/objects/InstanceObject.hpp
rwengine/src/objects/VehicleObject.cpp
rwengine/src/objects/VehicleObject.hpp

- LoaderCOL was just a series of bad decisions, entirely re-written to just support version 1 correctly
- Load triangle surface information so we can actually use it eventually
- Load CollisionModels directly into the model info for the model, saves having some other structures around

Physics cleanup

---

rwengine/src/items/Weapon.cpp
rwengine/src/objects/CharacterObject.cpp
rwengine/src/objects/CharacterObject.hpp
rwgame/RWGame.cpp
rwgame/RWGame.hpp
rwgame/State.cpp
rwgame/State.hpp
rwgame/states/DebugState.cpp
rwgame/states/DebugState.hpp
rwgame/states/IngameState.cpp
rwgame/states/IngameState.hpp

This lays the ground work for more complicated player controls, strafing etc. and moves responsibility for interpolating camera transformation into State.

Improve camera and look control

---

rwengine/CMakeLists.txt
rwengine/src/ai/TrafficDirector.cpp
rwengine/src/data/ModelData.hpp
rwengine/src/data/PedData.cpp
rwengine/src/data/PedData.hpp
rwengine/src/engine/GameData.cpp
rwengine/src/engine/GameData.hpp
rwengine/src/engine/SaveGame.cpp
rwengine/src/loaders/LoaderIDE.cpp
rwengine/src/loaders/LoaderIDE.hpp
rwgame/RWGame.cpp
tests/test_GameData.cpp
tests/test_object_data.cpp

- Prevent traffic from spawning in cutscenes
- Load ped stat data
- Load ped type relationship data
- Load ped groups

Ped improvements

---

rwengine/src/objects/VehicleObject.cpp
rwengine/src/render/ObjectRenderer.hpp

Small clean up compiler's log.

Removing two Wreorder warnings

---

rwengine/src/objects/CharacterObject.cpp
rwengine/src/script/modules/GTA3ModuleImpl.inl

repleace magic numbers constant variables.

fixing magic numbers in playAnimation()

---

rwengine/src/ai/CharacterController.hpp
rwengine/src/objects/CharacterObject.hpp
rwengine/src/objects/CutsceneObject.hpp
rwengine/src/objects/GameObject.hpp
rwengine/src/objects/InstanceObject.hpp
rwengine/src/objects/PickupObject.hpp
rwengine/src/objects/ProjectileObject.hpp
rwengine/src/objects/VehicleObject.hpp
rwgame/states/BenchmarkState.hpp
rwgame/states/DebugState.hpp
rwgame/states/IngameState.hpp
rwgame/states/LoadingState.hpp
rwgame/states/MenuState.hpp
rwgame/states/PauseState.hpp

Add missing override, this caused warnings.

add missing override

---

rwengine/src/BinaryStream.cpp
rwengine/src/TextureArchive.cpp
rwengine/src/data/InstanceData.hpp
rwengine/src/loaders/LoaderIDE.cpp
rwengine/src/loaders/LoaderIPL.cpp

I've found some snippets of code to edit in c++ 11 "style".
I've tried to keep readability as good as possible.

Replacing "new" operators with make_unique/shared

---

README.md

Replace mad with ffmpeg.
Build needs to be restarted. :(

Update Readme.md (FFmpeg)

---

rwengine/src/engine/Animator.cpp
rwengine/src/engine/GameWorld.cpp
rwengine/src/objects/CharacterObject.cpp
rwengine/src/objects/CharacterObject.hpp

Suggestions as usual are welcomed. ;)
This pull contains small improvements, but overall doesn't do anything big.

Various small changes

---

rwengine/src/script/modules/GTA3ModuleImpl.inl

While searching opcodes connected with text, I found math opcodes which can be easily implemented.

Implement math opcodes

---

rwengine/src/script/modules/GTA3ModuleImpl.inl

Reedited, now it should handle overlay of HighPriority text. Description in comments of commits.
Ref:
#121 
#129

Prevent occurrence text overlay

---

rwengine/src/engine/GameWorld.hpp
rwengine/src/objects/CharacterObject.cpp

Add implementation isPlayer function in CharacterObject.

implement isPlayer()

---

rwgame/RWGame.cpp

Pause chase when the game paused

---

rwengine/src/render/TextRenderer.cpp

On gtamodding.com is useful list:
https://www.gtamodding.com/wiki/GXT#Tokens

Fix text colors

---

rwengine/src/script/modules/GTA3ModuleImpl.inl

Small pull, it's practically copy and paste.
Edit. I've added one more bigger commit. It's still calque, but I'm not sure about int arg6/8.
And how think about angled area.

Implement missing opcodes "Is in area?"

---

CMakeLists.txt
rwengine/src/loaders/LoaderIDE.cpp
rwengine/src/loaders/WeatherLoader.cpp
rwengine/src/render/GameRenderer.cpp
rwengine/src/render/MapRenderer.cpp
rwengine/src/script/modules/GTA3ModuleImpl.inl
rwgame/DrawUI.cpp

Small pull, I found some unwanted conversion to double.

Fix double promotion

---

rwengine/src/ai/CharacterController.cpp
rwengine/src/engine/GameData.cpp
rwengine/src/objects/PickupObject.cpp
rwengine/src/objects/VehicleObject.cpp

Resolve cases found by gcc-5(travis), I don't why gcc 7.2 and clang are quiet.

Another pull with double promotion

---

rwengine/src/data/Chase.cpp
rwengine/src/data/Chase.hpp
rwengine/src/engine/GameData.cpp
rwengine/src/engine/GameData.hpp
rwengine/src/engine/SaveGame.cpp
rwengine/src/loaders/LoaderIFP.cpp
rwengine/src/loaders/LoaderIFP.hpp
rwengine/src/render/DebugDraw.cpp
rwengine/src/render/MapRenderer.cpp
rwengine/src/render/OpenGLRenderer.hpp
rwengine/src/render/TextRenderer.cpp
rwengine/src/render/WaterRenderer.cpp
rwgame/RWGame.cpp
rwlib/source/data/Clump.hpp

To think about:
- anonymous union
It prevents making reasonable contructor.
https://github.com/rwengine/openrw/blob/3c83e7cf52676dd27924bffb98713c712b4ded32/rwengine/src/script/ScriptMachine.cpp#L47
- opcode 0219
For example calling element nr size()-1  isn't thread safe.
https://github.com/rwengine/openrw/blob/512ac6f5eed3f6a356aac6bad3f28d8936faa25d/rwengine/src/script/modules/GTA3ModuleImpl.inl#L6280

Avoid making unnecessary copies

---

rwengine/src/engine/Animator.cpp
rwengine/src/engine/GameData.cpp
rwengine/src/engine/GameWorld.cpp
rwengine/src/objects/VehicleInfo.hpp
rwengine/src/render/DebugDraw.cpp
rwengine/src/render/GameRenderer.cpp
rwengine/src/render/ObjectRenderer.cpp
rwgame/GameConfig.cpp
rwgame/states/BenchmarkState.cpp

Empty has always computational complexity O(1).

Replace size() with empty() where possible.

---

rwengine/src/loaders/GenericDATLoader.cpp
rwengine/src/objects/InstanceObject.cpp
rwlib/source/gl/TextureData.hpp
rwlib/source/platform/FileIndex.cpp

When holes were plugged, some old snippets of code should be refreshed.

Use make_shared/unique.

---

rwengine/src/ai/DefaultAIController.hpp
rwengine/src/ai/PlayerController.hpp
rwengine/src/core/Logger.hpp
rwengine/src/dynamics/CollisionInstance.cpp
rwengine/src/dynamics/RaycastCallbacks.hpp
rwengine/src/engine/GameWorld.cpp
rwengine/src/objects/CharacterObject.hpp
rwengine/src/objects/CutsceneObject.hpp
rwengine/src/objects/InstanceObject.hpp
rwengine/src/objects/ItemPickup.hpp
rwengine/src/objects/PickupObject.hpp
rwengine/src/objects/ProjectileObject.hpp
rwengine/src/objects/VehicleObject.cpp
rwengine/src/objects/VehicleObject.hpp
rwengine/src/render/DebugDraw.hpp
rwengine/src/render/OpenGLRenderer.hpp
rwengine/src/script/ScriptMachine.hpp
rwgame/GameBase.hpp
rwgame/RWGame.hpp
rwgame/states/BenchmarkState.hpp
rwgame/states/DebugState.hpp
rwgame/states/IngameState.hpp
rwgame/states/LoadingState.hpp
rwgame/states/MenuState.hpp
rwgame/states/PauseState.hpp

Small cleanup. To think about - more functions are able to use c++11 const.
Edit I've found some more in VehicleObject. Done.

Remove refundant "virtual"

---

rwengine/src/render/OpenGLRenderer.cpp
rwengine/src/render/OpenGLRenderer.hpp
rwengine/src/script/SCMFile.hpp
rwlib/CMakeLists.txt
rwlib/source/loaders/LoaderDFF.cpp
rwlib/source/loaders/RWBinaryStream.hpp
rwlib/source/rw/bit_cast.cpp

In this pull I want to take care about one memory leak and undefined behavior.
Without virtual destructor: https://gist.github.com/ShFil119/a8dd2447957b9dc0dcd59f651315ebfc
With: https://gist.github.com/ShFil119/49403c30de189d07ec39d9c12065f6aa
Before: https://gist.github.com/ShFil119/d57738e91c9ee148689e85358f1241e1
After: https://gist.github.com/ShFil119/8c41e5c93392e7017b782f7eaecbc5ea
Edit I wanted open pull on my fork... I set tag work in progress.
To do:

Small fixes

---

rwengine/src/data/ModelData.hpp
rwengine/src/dynamics/CollisionInstance.cpp
rwengine/src/engine/GameWorld.cpp
rwengine/src/loaders/GenericDATLoader.cpp
rwengine/src/objects/InstanceObject.cpp
rwengine/src/objects/InstanceObject.hpp
rwengine/src/objects/VehicleObject.cpp
tests/test_Data.cpp

- Tidy up crusty code in Instance and Vehicle object classes.
- Fix spelling mistakes
- Placeholder for object collision effects.
- Fix #365

Object improvements

---

tests/test_Character.cpp
tests/test_Pickup.cpp

Error logs in commit's comment.

Fix UB in tests

---

.dockerignore
.travis.yml
cmake/ctest/travis_script.ctest
scripts/docker/arch_latest.docker
scripts/docker/docker_build.sh
scripts/docker/docker_tool.py
scripts/docker/docker_travis.sh
scripts/docker/fedora_latest.docker
scripts/docker/ubuntu_latest.docker

This is a continuation of #353. Which is now more urgent as the library versions available on Travis are too old.
- Rebase onto master
- Add a script to perform local cross-compilation (may be useful to avoid breaking builds on other distributions or on windows).

Travis docker

---

rwengine/src/data/ModelData.hpp
rwengine/src/data/Weather.cpp
rwengine/src/engine/GameWorld.cpp
rwengine/src/engine/GameWorld.hpp
rwengine/src/loaders/LoaderIDE.cpp
rwengine/src/objects/VehicleObject.cpp
rwengine/src/objects/VehicleObject.hpp

This implements the handling of all Component Rules used in III. Right now Rule 2 is somewhat useless, but with dynamic weather it should just start to work.

Vehicle Components

---

rwengine/src/ai/AIGraph.cpp
rwengine/src/data/GameTexts.cpp
rwengine/src/dynamics/CollisionInstance.cpp
rwengine/src/engine/GameState.cpp
rwengine/src/engine/GameWorld.cpp
rwengine/src/engine/SaveGame.cpp
rwengine/src/engine/ScreenText.cpp
rwengine/src/loaders/LoaderIFP.cpp
rwengine/src/loaders/WeatherLoader.cpp
rwengine/src/objects/CharacterObject.cpp
rwengine/src/render/TextRenderer.cpp
rwengine/src/render/TextRenderer.hpp
rwengine/src/render/ViewFrustum.hpp
rwengine/src/script/SCMFile.cpp
rwgame/MenuSystem.hpp
rwgame/RWGame.cpp
rwlib/source/loaders/LoaderIMG.cpp

Small clean up. It should increases readability a bit.  
And most important - has this pull a meaning or value? Do you want range loops?

Use range loop

---

rwgame/states/DebugState.cpp
rwgame/states/DebugState.hpp

Sets the weather, simple as that. 🙂

Create debugstate submenu weather.

---

rwengine/src/engine/GameWorld.cpp

Small and quick fix for a segfault.
This kind of fixes #274 as the game did crash upon entering the vehicle, not spawning (this was probably fixed before).

Fix seat assignment on boats.

---

scripts/docker/fedora_latest.docker

Use Fedora Rawhide
See https://hub.docker.com/_/fedora/

script: Use Fedora rawhide instead of latest stable release

---

rwengine/src/script/modules/GTA3ModuleImpl.inl

As requested [here](https://github.com/rwengine/openrw/pull/342#issuecomment-355485742)

Convert tabs to spaces of rwengine/src/script/modules/GTA3ModuleImpl.inl

---

rwengine/src/audio/SoundManager.cpp
rwengine/src/audio/SoundManager.hpp

Exceptionally I serve you something finished. (I hope.)
For future task:
- Divide sounds into groups. For example we want to play menu's sounds in menu. ;)
to do:

Allow to pause and resume sounds

---

rwengine/src/ai/CharacterController.hpp
rwengine/src/audio/SoundManager.cpp
rwengine/src/data/ModelData.hpp
rwengine/src/engine/GameData.cpp
rwengine/src/engine/GameWorld.cpp
rwengine/src/loaders/LoaderIDE.cpp
rwengine/src/loaders/LoaderIFP.hpp
rwengine/src/objects/CutsceneObject.cpp
rwengine/src/objects/InstanceObject.cpp
rwengine/src/objects/VehicleObject.cpp
rwengine/src/render/GameRenderer.cpp
rwengine/src/render/GameRenderer.hpp
rwengine/src/render/OpenGLRenderer.cpp
rwengine/src/render/OpenGLRenderer.hpp
rwengine/src/render/TextRenderer.cpp
rwengine/src/render/ViewCamera.hpp
rwengine/src/render/VisualFX.cpp
rwengine/src/render/WaterRenderer.cpp
rwengine/src/render/WaterRenderer.hpp
rwengine/src/script/ScriptMachine.hpp
rwgame/DrawUI.cpp
rwgame/State.cpp
rwgame/State.hpp
rwgame/main.cpp
rwgame/states/IngameState.cpp
rwlib/source/data/Clump.cpp
rwlib/source/data/Clump.hpp
rwlib/source/loaders/LoaderDFF.cpp
rwlib/source/loaders/LoaderSDT.cpp

Various, small changes

---

rwengine/src/objects/CharacterObject.cpp
rwengine/src/render/ObjectRenderer.cpp
rwengine/src/script/ScriptTypes.cpp

It should increase stability a bit.

Some potential deference of null pointers

---

rwengine/src/script/ScriptMachine.cpp
rwengine/src/script/ScriptMachine.hpp
rwengine/src/script/modules/GTA3ModuleImpl.inl

Hi!
Not much to say, really. Implemented using C++ std::{random_device,mt19937}.
I originally wrote this about a month ago or two, and thought I would just PR this now - I do have finals at the moment and not really a lot of time. And before this code rots ..
Greets!

Implement random number opcodes [0098, 0099, 0208, 0209].

---

rwengine/src/objects/VehicleObject.cpp
rwengine/src/objects/VehicleObject.hpp
rwengine/src/render/GameRenderer.hpp

I am getting familiar with the code and I fixed some TODOs along the way. I know I should separate different issues into multiple PRs, but these were trivial ones so I thought I'd do it in one go (will separate them if you insist).
- Getting into taxi gives you $25, tested. (~~Though I think each taxi should only give the money once, should I add a check?~~ - did this)
- Removed redundant condition, tested.
- Added some documenting comment after inspecting DFF models with Blender.

Address simple TODOs in the code

---

rwengine/src/objects/VehicleObject.cpp

Access `engine` directly instead through `character->engine`

---

rwengine/src/engine/GameWorld.cpp
rwengine/src/objects/InstanceObject.cpp
rwengine/src/objects/InstanceObject.hpp

Until now buoys would just fall down, we need to apply the force with an impulse to make it work. To update the objects in debug mode, a tickPhysics function had to be created, like the vehicles already use.

Make buoys float again

---

rwgame/states/DebugState.cpp
rwgame/states/DebugState.hpp

Added debug menu to start missions
Only works from new game or loaded save otherwise script system breaks badly

[Ready] Missions debug menu

---

rwengine/src/script/modules/GTA3ModuleImpl.inl

[Ready] Mostly game stats related opcodes

---

rwengine/src/script/ScriptFunctions.hpp
rwengine/src/script/modules/GTA3ModuleImpl.inl

[Ready] Improved mission clean up logic and implemented related opcodes

---

rwgame/game.hpp

It should reduce level of perceptibility physics bugs and tearing non-interpolated objects.

Increase tickrate to 60 times per second

---

rwengine/src/ai/PlayerController.cpp
rwengine/src/engine/GameWorld.cpp
rwengine/src/engine/GameWorld.hpp
rwengine/src/script/modules/GTA3ModuleImpl.inl

Small refactor, fixed 0395 opcode, game now clears world on player restart.

Clear world on player restart

---

rwengine/src/script/ScriptFunctions.hpp
rwengine/src/script/ScriptMachine.cpp
rwengine/src/script/ScriptMachine.hpp
rwengine/src/script/modules/GTA3Module.cpp
rwengine/src/script/modules/GTA3ModuleImpl.inl

As written by @husho in #411.
Continuation of #435.

Implemented some various opcodes

---

rwengine/src/script/modules/GTA3ModuleImpl.inl

Updated according to requested changes and comments in #363

New opcodes as written by @aldoxtor

---

rwengine/src/ai/PlayerController.cpp

Fixed: mission is not restarting if player is in vehicle

---

rwengine/src/script/ScriptMachine.cpp

Fixed crash on new game, fixed missions not failing on death/arrest

---

rwengine/src/engine/GameState.cpp
rwgame/RWGame.cpp
rwgame/RWGame.hpp

Ripped off from pickups PR and I did improve it a little

Added support for variable game speed

---

rwengine/src/script/modules/GTA3ModuleImpl.inl

All locate opcodes are implemented at this point

Locate opcodes

---

rwengine/src/engine/GameWorld.cpp
rwengine/src/engine/GameWorld.hpp
rwengine/src/script/ScriptMachine.cpp
rwengine/src/script/modules/GTA3ModuleImpl.inl
rwgame/RWGame.cpp
rwgame/RWGame.hpp
rwgame/states/DebugState.cpp
rwgame/states/IngameState.cpp

[Ready] Refactor: moved getPlayer to World class

---

rwengine/src/ai/PlayerController.cpp
rwengine/src/ai/PlayerController.hpp
rwengine/src/engine/GameState.cpp
rwengine/src/engine/GameState.hpp
rwengine/src/render/GameRenderer.cpp
rwengine/src/script/modules/GTA3ModuleImpl.inl
rwgame/RWGame.cpp

[Ready] Fade fix part 2

---

rwengine/src/ai/PlayerController.cpp
rwengine/src/ai/PlayerController.hpp
rwengine/src/script/modules/GTA3ModuleImpl.inl

Removed wrong functionality from 0373, added 03ef.

Redid opcodes related to player input and cutscenes

---

rwengine/src/script/modules/GTA3ModuleImpl.inl

Fixes crash on vigilante and paramedic start
Enables 01e9, 01ea, 0376 opcodes

Fix paramedic & vigilante submissions

---

rwengine/src/objects/CharacterObject.cpp

rwengine: check whether character is player

---

rwengine/src/engine/GameState.cpp
rwengine/src/engine/GameState.hpp
rwgame/RWGame.cpp

Previous PR: https://github.com/rwengine/openrw/pull/495

Implement some cheats and showing cheat activated message

---

rwengine/src/objects/VehicleObject.cpp

There were some minor points of improvement pointed out in the PR #349 . Here I've tried addressing those.
Closes #518 .

Fix #349 "Smooth vehicle steering"

---

rwengine/src/ai/AIGraph.cpp
rwengine/src/ai/AIGraph.hpp
rwengine/src/ai/AIGraphNode.hpp
rwengine/src/ai/CharacterController.cpp
rwengine/src/ai/CharacterController.hpp
rwengine/src/ai/DefaultAIController.cpp
rwengine/src/ai/TrafficDirector.cpp
rwengine/src/data/PathData.hpp
rwengine/src/loaders/LoaderIDE.cpp
rwengine/src/objects/VehicleObject.cpp
rwengine/src/objects/VehicleObject.hpp
rwengine/src/script/ScriptFunctions.hpp
rwengine/src/script/modules/GTA3ModuleImpl.inl
rwgame/RWGame.cpp

This is my first rather long pull request, so criticism is as always appreciated.
The main purpose of this commit is to implement, as already said, basic traffic.
I did change some other sections, which i will explain.
Basically the vehicles spawn similar like the pedestrians, but this time in between two nodes, so that we can set the orientation.
I don't know whether there is also a file like `pedgrp.dat` for vehicles, so for now I hardcoded a list with vehicles to spawn.
A new goal - TrafficDriver was added, and a new Activity - DriveTo.
For the rudimentary control I needed two new functions `isInFront(...)` and `isOnSide(...)` which test whether a point is in front or at the side of the vehicle.
As updating the angle of the steering takes too long for this rudimentary control to work, …

[Ready] Basic traffic

---

rwengine/src/ai/DefaultAIController.hpp
rwengine/src/ai/PlayerController.hpp
rwengine/src/core/Logger.hpp
rwengine/src/dynamics/RaycastCallbacks.hpp
rwengine/src/objects/CharacterObject.hpp
rwengine/src/objects/CutsceneObject.hpp
rwengine/src/objects/InstanceObject.hpp
rwengine/src/objects/ProjectileObject.hpp
rwengine/src/objects/VehicleObject.cpp
rwengine/src/objects/VehicleObject.hpp
rwengine/src/render/DebugDraw.hpp
rwengine/src/render/OpenGLRenderer.hpp
rwgame/RWGame.hpp
rwgame/states/BenchmarkState.hpp
rwgame/states/DebugState.hpp
rwgame/states/IngameState.hpp
rwgame/states/LoadingState.hpp
rwgame/states/MenuState.hpp
rwgame/states/PauseState.hpp

It lets compiler to make extra optimization.
See:
https://godbolt.org/g/ASLk4B

Mark classes as final

---

rwengine/src/objects/CharacterObject.cpp
rwengine/src/objects/CharacterObject.hpp

Signed-off-by: Paul Kocialkowski <contact@paulk.fr>

Improve jump by getting inertia from the previous movement

---

rwengine/src/objects/VehicleObject.cpp
rwengine/src/objects/VehicleObject.hpp
rwgame/states/DebugState.cpp

This is an attempt at making vehicles more usable in the game, with improvements to various aspects of driving.

Various vehicle improvements

---

rwgame/RWGame.cpp

Fix segfault when script timer runs out

---

rwcore/loaders/LoaderSDT.cpp
rwcore/loaders/LoaderSDT.hpp
rwengine/CMakeLists.txt
rwengine/src/audio/SfxParameters.cpp
rwengine/src/audio/SfxParameters.hpp
rwengine/src/audio/SoundManager.cpp
rwengine/src/audio/SoundManager.hpp
rwengine/src/audio/SoundSource.cpp
rwengine/src/audio/SoundSource.hpp
rwengine/src/engine/GameWorld.cpp
rwengine/src/script/ScriptTypes.cpp
rwengine/src/script/ScriptTypes.hpp
rwengine/src/script/modules/GTA3ModuleImpl.inl
rwgame/RWGame.cpp

Sfx - ScriptObject, metadata, opcodes, listener position

---

cmake_configure.cmake
rwcore/platform/FileIndex.cpp
rwcore/rw/abort.cpp
rwcore/rw/debug.hpp
rwengine/src/audio/SoundManager.cpp
rwengine/src/core/Profiler.hpp
rwengine/src/engine/SaveGame.cpp
rwengine/src/render/OpenGLRenderer.cpp
rwengine/src/render/OpenGLRenderer.hpp
rwengine/src/render/TextRenderer.cpp
rwgame/RWGame.cpp

- use `#ifdef RW_PROFILER` instead of `#if RW_PROFILER`
- use `#ifdef RW_DEBUG` instead of `#if RW_DEBUG`
- use `-std=c++14` instead of `-std=g++14`
- throw std::runtime_error when illegal font is loaded
- set windows version explicitly (=Windows Vista)

cmake updates

---

rwengine/src/objects/CharacterObject.cpp
rwengine/src/objects/CharacterObject.hpp
rwengine/src/objects/PickupObject.cpp
rwengine/src/objects/PickupObject.hpp
rwengine/src/objects/ProjectileObject.cpp
rwengine/src/objects/ProjectileObject.hpp
rwengine/src/objects/VehicleObject.cpp
rwengine/src/objects/VehicleObject.hpp
rwgame/states/IngameState.cpp
tests/test_Vehicle.cpp

It removes some nasty things:
https://github.com/rwengine/openrw/compare/master...ShFil119:remove_raw_ptrs_from_objects?expand=1#diff-a996c0379ea38c4fa42528c76c60ec03R753
https://github.com/rwengine/openrw/compare/master...ShFil119:remove_raw_ptrs_from_objects?expand=1#diff-a996c0379ea38c4fa42528c76c60ec03R589

Remove raw ptrs from game objects

---

rwcore/data/Clump.cpp
rwcore/data/Clump.hpp
rwengine/src/engine/GameData.cpp
rwengine/src/engine/GameData.hpp
rwengine/src/engine/SaveGame.cpp
rwengine/src/loaders/GenericDATLoader.cpp
rwengine/src/objects/CharacterObject.cpp
rwengine/src/objects/CutsceneObject.cpp
rwengine/src/objects/VehicleObject.cpp
rwengine/src/render/DebugDraw.cpp
rwengine/src/render/DebugDraw.hpp
rwengine/src/render/OpenGLRenderer.cpp
rwengine/src/script/SCMFile.cpp
rwengine/src/script/SCMFile.hpp
rwengine/src/script/ScriptFunctions.cpp
rwengine/src/script/ScriptMachine.cpp
rwengine/src/script/ScriptMachine.hpp
rwengine/src/script/ScriptTypes.cpp
rwengine/src/script/modules/GTA3ModuleImpl.inl
rwgame/RWGame.cpp
rwgame/RWGame.hpp
rwgame/states/DebugState.cpp

Bigger tasks still to do:
- AIGraph
- objects of GameWorld
- GameObject (itself)
- Animation

Minor memory improvements

---

rwengine/src/engine/GameWorld.cpp

Use lambda for removing VisualFX

---

rwcore/gl/DrawBuffer.cpp
rwcore/gl/GeometryBuffer.hpp
rwengine/src/render/GameRenderer.hpp

Minor stuff

---

rwengine/src/audio/SoundManager.cpp
rwengine/src/audio/SoundManager.hpp

Implement basic sound volume managment

---

rwengine/src/ai/CharacterController.cpp
rwengine/src/ai/PlayerController.cpp
rwengine/src/engine/GameWorld.cpp
rwengine/src/engine/GameWorld.hpp
rwengine/src/engine/Garage.cpp
rwengine/src/engine/Payphone.cpp
rwengine/src/items/Weapon.cpp
rwengine/src/objects/ProjectileObject.hpp
rwengine/src/script/modules/GTA3ModuleImpl.inl
rwgame/RWGame.cpp
rwgame/states/DebugState.cpp
tests/test_GameWorld.cpp
tests/test_Globals.hpp

Tweaked a bit `test_GameWorld.cpp` actual version would delete world twice.

Game objects as unique ptrs

---

rwengine/src/objects/VehicleObject.cpp

See:
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=87658
Should help with #643.

Replace insert with emplace

---

rwcore/fonts/FontMap.cpp
rwengine/src/audio/SoundManager.cpp
rwengine/src/engine/Animator.cpp
rwengine/src/engine/GameState.cpp
rwengine/src/engine/GameWorld.cpp
rwengine/src/objects/VehicleObject.cpp
rwengine/src/script/modules/GTA3ModuleImpl.inl
rwgame/GameConfig.cpp
rwgame/GameInput.cpp
rwgame/RWGame.cpp
rwgame/states/DebugState.cpp

It should increase readability a bit. ;)

Start using structured bindings

---

.travis.yml

Update xcode version to 10.1

---

rwengine/src/audio/SoundManager.cpp
rwengine/src/audio/SoundManager.hpp
rwengine/src/data/CutsceneData.hpp
rwengine/src/engine/GameData.cpp
rwengine/src/engine/GameData.hpp
rwengine/src/engine/GameState.hpp
rwengine/src/engine/GameWorld.cpp
rwengine/src/engine/GameWorld.hpp
rwengine/src/script/modules/GTA3ModuleImpl.inl
rwgame/states/IngameState.cpp

First commit replaces raw ptr with unique ptr.
Second one implements flushing resources (animations and sound) when cutscene ends.
Should hep with #428. Requesting reviews, especially from @darkf. ;)

Cutscenes cleanup

---

rwengine/src/objects/InstanceObject.cpp

Send all bullet rigid bodies belonging to buildings and objects to sleep when loading.

Quick fix for choppy performance at startup

---

rwengine/src/ai/CharacterController.cpp
rwengine/src/data/ModelData.hpp
rwengine/src/engine/GameData.cpp
rwengine/src/engine/GameData.hpp
rwengine/src/engine/GameWorld.cpp
rwengine/src/items/Weapon.hpp
rwengine/src/loaders/GenericDATLoader.cpp
rwengine/src/loaders/GenericDATLoader.hpp
rwengine/src/objects/InstanceObject.cpp
rwengine/src/objects/InstanceObject.hpp
rwengine/src/objects/PickupObject.cpp
rwengine/src/objects/PickupObject.hpp
rwengine/src/objects/ProjectileObject.hpp
rwengine/src/objects/VehicleInfo.hpp
rwengine/src/objects/VehicleObject.cpp
rwengine/src/objects/VehicleObject.hpp
rwengine/src/render/ObjectRenderer.cpp
rwgame/HUDDrawer.cpp
rwgame/states/DebugState.cpp
rwgame/states/IngameState.cpp
tests/test_Data.cpp
tests/test_Pickup.cpp
tests/test_Weapon.cpp

Do you prefer using const ref or raw ptr?

Reduce nr of dynamic allocations

---

rwengine/src/engine/Animator.cpp
rwengine/src/loaders/LoaderIFP.cpp
rwengine/src/loaders/LoaderIFP.hpp
rwengine/src/objects/CharacterObject.cpp
tests/test_Animation.cpp

Should improve a bit performance.

[improvement] Contiguous memory for `bones` container

---

rwcore/rw/forward.hpp
rwengine/src/data/Chase.cpp
rwengine/src/data/Chase.hpp
rwengine/src/loaders/LoaderIFP.cpp
rwengine/src/script/ScriptModule.hpp
rwengine/src/script/modules/GTA3Module.cpp
rwengine/src/script/modules/GTA3ModuleImpl.inl

I've found some more spots to clean.

More unordered_map reserve

---

rwgame/MenuSystem.hpp
rwgame/State.hpp
rwgame/states/DebugState.cpp
rwgame/states/DebugState.hpp
tests/test_State.cpp

Convert Menu instances to std::optional

---

rwgame/MenuSystem.hpp
rwgame/State.cpp
rwgame/State.hpp
rwgame/states/DebugState.cpp
rwgame/states/DebugState.hpp
rwgame/states/MenuState.cpp
rwgame/states/PauseState.cpp
tests/test_Menu.cpp

It also fixes weird behavior which can happen it debug mode on master. (freeze/crash) Caused by #667.

Further refactor of menu managment

---

rwgame/RWGame.cpp
rwgame/RWGame.hpp
rwgame/StateManager.hpp
rwgame/states/IngameState.cpp
rwgame/states/MenuState.cpp
rwgame/states/PauseState.cpp

This allows RWGame to be relaunched multiple times in the same process

rwgame: make StateManager non-static

---

rwengine/CMakeLists.txt
rwengine/src/ai/CharacterController.cpp
rwengine/src/dynamics/HitTest.cpp
rwengine/src/dynamics/HitTest.hpp
rwengine/src/objects/VehicleObject.cpp
rwengine/src/objects/VehicleObject.hpp
rwengine/src/render/DebugDraw.hpp
rwgame/RWGame.cpp
tests/CMakeLists.txt
tests/test_HitTest.cpp

- Provide a tested API for performing area checks against physical objects.
This functionality can be re-used for weapon area check.
Future work
- Document AI vehicle behaviour.

Use collision detection for AI vehicle behaviour

---

rwgame/RWConfig.cpp
tests/test_Config.cpp

- fixes https://github.com/rwengine/openrw/pull/676#issuecomment-455022268
bool argument options such as `--invert_y`, `--fullscreen`, ... did not work
- work around boostorg/program_options#72

RWconfig fixes

---

rwengine/src/render/ObjectRenderer.cpp

https://github.com/rwengine/openrw/issues/694
Now rotation speed is almost exactly as in original GTA III on my pc.

Pickups speed adjusted. Closes #694

---

rwcore/data/Clump.hpp
rwcore/gl/TextureData.hpp
rwcore/loaders/LoaderDFF.cpp
rwcore/loaders/LoaderDFF.hpp
rwcore/loaders/LoaderTXD.cpp
rwcore/rw/debug.hpp
rwengine/src/audio/alCheck.cpp
rwengine/src/core/Logger.cpp
rwengine/src/core/Logger.hpp
rwengine/src/engine/GameData.cpp
rwengine/src/engine/GameData.hpp
rwengine/src/engine/GameWorld.cpp
rwengine/src/engine/SaveGame.cpp
rwengine/src/loaders/LoaderIPL.cpp
rwengine/src/loaders/LoaderIPL.hpp
rwengine/src/objects/ProjectileObject.cpp
rwengine/src/render/DebugDraw.cpp
rwengine/src/render/GameRenderer.cpp
rwengine/src/render/MapRenderer.cpp
rwengine/src/render/TextRenderer.cpp
rwengine/src/render/VisualFX.hpp
rwengine/src/render/WaterRenderer.cpp
rwgame/HUDDrawer.cpp
rwgame/RWConfig.cpp
rwgame/RWGame.cpp
rwgame/states/BenchmarkState.cpp
rwgame/states/DebugState.cpp
rwgame/states/PauseState.cpp
rwviewer/views/ModelViewer.cpp
tests/test_LoaderIPL.cpp

Commit 07972a7fa76462351689ddff6c2eb5f72446bef2 is temporary(?) solution, planning use weak_ptr + shared_ptrs. It's nicely specifying where weak_ptr should be used. Or if you prefer I can drop this commit. ;)

Various (smaller changes)

---

cmake/modules/FindFFmpeg.cmake
rwengine/src/audio/SoundManager.cpp
rwengine/src/audio/SoundManager.hpp
rwengine/src/audio/SoundSource.cpp
rwengine/src/audio/SoundSource.hpp
rwengine/src/script/ScriptTypes.cpp
rwengine/src/script/modules/GTA3ModuleImpl.inl
tests/CMakeLists.txt
tests/test_AudioLoading.cpp
tests/test_Sound.cpp

Not sure about naming convention(especially about `Wrap`).

Divide SoundSource (for future streaming)

---

rwengine/src/engine/GameData.cpp

(it should fix issue on master)

Avoid overwriting generic textures with splashes

---

rwgame/GameBase.cpp
rwgame/RWGame.cpp

Close window in parent class (GameBase)

---

rwengine/src/render/GameRenderer.cpp
rwengine/src/render/WaterRenderer.cpp

Now water rendered before world objects.
https://github.com/rwengine/openrw/issues/71

Fix: https://github.com/rwengine/openrw/issues/71

---

conanfile.py
scripts/docker/docker_tool.py

- Override package incompatibility.
- santiziers need ptrace, so set the capability on containers.

Fix conan build

---

rwengine/src/audio/SoundSource.cpp
rwengine/src/audio/SoundSource.hpp

Works. There are issues with the tests, but that's unrelated to the fixes.

ffmpeg 7.1 support
